/'*****
License
--------------
Copyright © 2017 Bill & Melinda Gates Foundation
The Mojaloop files are made available by the Bill & Melinda Gates Foundation under the Apache License, Version 2.0 (the "License") and you may not use these files except in compliance with the License. You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, the Mojaloop files are distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Contributors
--------------
This is the official list of the Mojaloop project contributors for this file.
Names of the original copyright holders (individuals or organizations)
should be listed with a '*' in the first column. People who have
contributed from an organization can be listed under the organization
that actually holds the copyright for their contributions (see the
Gates Foundation organization for an example). Those individuals should have
their names indented and be marked with a '-'. Email address can be added
optionally within square brackets <email>.
* Gates Foundation

- Name Surname <name.surname@gatesfoundation.com>
--------------
******'/

@startuml
' declaring skinparam
skinparam sequenceMessageAlign center
skinparam shadowing false
skinparam defaultFontName Verdana
skinparam monochrome true
skinparam SequenceLifeLineBackgroundColor WhiteSmoke
skinparam SequenceLifeLineBorderColor Black
skinparam ParticipantFontStyle Bold
skinparam ParticipantFontSize 20
skinparam ParticipantBackgroundColor WhiteSmoke
skinparam sequencearrowcolor Black

hide footbox

' declare title
' title HTTP POST call flow

' Actor Keys:
' participant - FSP, Peer FSP and Optional Switch

' declare actors
participant "\nFSP" as FSP
participant "Optional\nSwitch" as Switch
participant "Peer\nFSP" as PEERFSP

' start flow
FSP ->> Switch: **POST /service**\n(Service information, ID)
activate FSP
activate Switch
FSP <<[#Red]-- Switch : **HTTP 202** (Accepted)
Switch ->> PEERFSP: **POST /service**\n(Service information, ID)
activate PEERFSP
Switch <<[#Red]-- PEERFSP: **HTTP 202** (Accepted)
PEERFSP -> PEERFSP: Create service object\naccording to request
Switch <<- PEERFSP: **PUT /service/**//<ID>//\n(Service object information)
Switch --[#Red]>> PEERFSP: **HTTP 200** (OK)
deactivate PEERFSP
FSP <<- Switch: **PUT /service/**//<ID>//\n(Service object information)
FSP --[#Red]>> Switch: **HTTP 200** (OK)
deactivate Switch
FSP -> FSP: Handle service object information
FSP -[hidden]> Switch
deactivate FSP
@enduml
