@startuml
Title Request Quote Creation
participant "Payer FSP" as PayerFSP
participant "Switch\n[Quoting\nService]" as Switch
database "Central Store" as DB
participant "Payee FSP" as PayeeFSP
autonumber

note over PayerFSP, Switch: Payer FSP sends request for quote \nto Payee FSP via the Switch
PayerFSP -\ Switch: POST /quotes
note right of Switch #aaa
    Validate request against 
    Mojaloop interface specification
    **<color #red>Error code: 300x, 310x</color>**
    **<color #red>HTTP error response code: 4xx</color>**
end note
Switch -> Switch: Schema validation
PayerFSP \-- Switch: 202 Accepted
|||
Switch -> Switch: Quote request validation (rules engine etc.)
|||
alt SimpleRoutingMode === FALSE
    Switch -> Switch: Duplicate check
    |||
    alt Request is a duplicate but not a resend
    |||
        note left of Switch
            Switch returns error back to Payer FSP
            <color #red>**Error code: 3106**</color>
        end note
        PayerFSP /- Switch: PUT /quotes/{ID}/error
        PayerFSP --/ Switch: 200 OK
    |||
    else Request is a duplicate and a resend
        Switch -> Switch: Switch handles resend scenario
    end
    |||
    Switch -\ DB: Persist quote request
    activate DB
        hnote over DB
            quoteDuplicateCheck
            transactionReference
            quote
            quoteParty
            quoteExtension
            geoCode
        end hnote
    Switch \-- DB: Quote request saved
    deactivate DB
end
|||
alt SimpleRoutingMode === TRUE
    Switch -> Switch: Use fspiop-destination header to retrieve quotes endpoint for Payee FSP
else SimpleRoutingMode === FALSE
    Switch -> Switch: Retireve Payee FSP endpoint using quote party information
end
|||
alt Payee quotes endpoint found
    note right of Switch: Switch forwards quote request to Payee FSP
    Switch -\ PayeeFSP: POST /quotes
    Switch \-- PayeeFSP: 202 OK

    PayeeFSP -> PayeeFSP: Payee FSP presists and calculates quote
    alt Payee quotes processing successful
        note left of PayeeFSP: Payee FSP sends quote response back to Payer FSP via the Switch
        Switch /- PayeeFSP: PUT /quotes/{ID}
        Switch --/ PayeeFSP: 200 OK

        Switch -> Switch: Validate quote response
        alt SimpleRoutingMode === FALSE
            Switch -> Switch: Duplicate check
            alt Response is duplicate but not a resend
                Switch -\ PayeeFSP: PUT /quotes/{ID}/error
                Switch \-- PayeeFSP: 200 OK
            end
            alt Response is a duplicate and a resend
                Switch -> Switch: Switch handles resend scenario
            end
            Switch -\ DB: Persist quote response
            activate DB
            hnote over DB
                quoteResponse
                quoteDuplicateCheck
                quoteResponseIlpPacket
                geoCode
                quoteExtension
            end hnote
            Switch \-- DB: Quote response saved
            deactivate DB
        end
        note left of Switch: Switch forwards quote response to Payer FSP
        PayerFSP /- Switch: PUT /quotes/{ID}
        PayerFSP --/ Switch: 200 OK
    else Payee rejects quotes or encounters and error
        note left of PayeeFSP: Payee FSP sends error callback to Payer FSP via the Switch
        Switch /- PayeeFSP: PUT /quotes/{ID}/error
        Switch --/ PayeeFSP: 200 OK
        alt SimpleRoutingMode === FALSE
            Switch -\ DB: Store quote error
            activate DB
            hnote over DB
                quoteError
            end hnote
            Switch \-- DB: Quote error saved
            deactivate DB
        end
        note left of Switch: Switch forwards error callback to Payer FSP
        PayerFSP /- Switch: PUT /quotes/{ID}/error
        PayerFSP --/ Switch: 200 OK
    end
else Payee FSP quotes endpoint not found
    note left of Switch: Switch sends an error callback to Payer FSP \n <color #red>**Error code: 3201**</color>
    PayerFSP /- Switch: PUT /quotes/{ID}/error
    PayerFSP --\ Switch: 200 OK
end

@enduml
