/'*****
License
--------------
Copyright © 2017 Bill & Melinda Gates Foundation
The Mojaloop files are made available by the Bill & Melinda Gates Foundation under the Apache License, Version 2.0 (the "License") and you may not use these files except in compliance with the License. You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, the Mojaloop files are distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Contributors
--------------
This is the official list of the Mojaloop project contributors for this file.
Names of the original copyright holders (individuals or organizations)
should be listed with a '*' in the first column. People who have
contributed from an organization can be listed under the organization
that actually holds the copyright for their contributions (see the
Gates Foundation organization for an example). Those individuals should have
their names indented and be marked with a '-'. Email address can be added
optionally within square brackets <email>.
* Gates Foundation

- Name Surname <name.surname@gatesfoundation.com>
--------------
******'/

@startuml

' declaring skinparam
skinparam sequenceMessageAlign center
skinparam shadowing false
skinparam defaultFontName Verdana
skinparam monochrome true
skinparam SequenceLifeLineBackgroundColor WhiteSmoke
skinparam SequenceLifeLineBorderColor Black
skinparam ParticipantFontStyle Bold
skinparam ParticipantFontSize 20
skinparam ParticipantBackgroundColor WhiteSmoke
skinparam ArrowColor Black

hide footbox

' declare title
' title Handling of error callback from POST /transfers

' Actor Keys:
' participant - FSP(Payer/Payee) and Switch


' declare actors
participant "Payer\nFSP" as PayerFSP
participant "Optional\nSwitch" as Switch
participant "Payee\nFSP" as PayeeFSP

' start flow
autonumber 1 1 "<b>[0]"
activate PayerFSP
PayerFSP -> PayerFSP: Reserve transfer from Payer\naccount to Switch account
PayerFSP ->> Switch: **POST /transfers**\n(Transfer ID, condition, ILP Packet\nincluding transaction details)
activate Switch
autonumber stop
PayerFSP <<-- Switch: **HTTP 202** (Accepted)
Switch -> Switch: Reserve transfer from\nPayer FSP to Payee FSP
autonumber resume
Switch ->> PayeeFSP: **POST /transfers**\n(Transfer ID, condition, ILP Packet\nincluding transaction details)
activate PayeeFSP
autonumber stop
Switch <<-- PayeeFSP: **HTTP 202** (Accepted)
PayeeFSP -> PayeeFSP: Some processing error occurs,\ne.g. a limit breach
autonumber resume
Switch <<- PayeeFSP: **PUT /transfers/**<i><ID></i>**/error**
autonumber stop
Switch -->> PayeeFSP: **HTTP 200** (OK)
deactivate PayeeFSP
Switch -> Switch: Cancel transfer from\nPayer FSP to Payee FSP
autonumber resume
PayerFSP <<- Switch: **PUT /transfers/**<i><ID></i>**/error**\n(Error information)
autonumber stop
PayerFSP -->> Switch: **HTTP 200** (OK)
deactivate Switch
PayerFSP -> PayerFSP: Cancel transfer from Payer\naccount to Payee FSP account
PayerFSP -[hidden]> Switch
deactivate PayerFSP
@enduml
