/'*****
License
--------------
Copyright © 2017 Bill & Melinda Gates Foundation
The Mojaloop files are made available by the Bill & Melinda Gates Foundation under the Apache License, Version 2.0 (the "License") and you may not use these files except in compliance with the License. You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, the Mojaloop files are distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Contributors
--------------
This is the official list of the Mojaloop project contributors for this file.
Names of the original copyright holders (individuals or organizations)
should be listed with a '*' in the first column. People who have
contributed from an organization can be listed under the organization
that actually holds the copyright for their contributions (see the
Gates Foundation organization for an example). Those individuals should have
their names indented and be marked with a '-'. Email address can be added
optionally within square brackets <email>.
* Gates Foundation

- Name Surname <name.surname@gatesfoundation.com>
--------------
******'/

@startuml

' declaring skinparam
skinparam sequenceMessageAlign center
skinparam shadowing false
skinparam defaultFontName Verdana
skinparam monochrome true
skinparam SequenceLifeLineBackgroundColor WhiteSmoke
skinparam SequenceLifeLineBorderColor Black
skinparam ParticipantFontStyle Bold
skinparam ParticipantFontSize 20
skinparam ParticipantBackgroundColor WhiteSmoke

hide footbox

' declare title
' title Error handling from client using GET request

' Actor Keys:
' participant - Client and Server


' declare actors
participant "Client" as client
participant "Server" as server

' start flow
autonumber 1 1 "<b>[0]"
client ->> server: **POST /service**
activate client
activate server
client <<-- server: **HTTP 202** (Accepted)
'autonumber stop
client -> client: No update received within\nreasonable time period,\ncheck status
'autonumber resume
client ->> server: **GET /service**<i><ID></i>
autonumber stop
client <<-- server: **HTTP 202** (Accepted)
autonumber resume
client <<- server: **PUT /service/**<i><ID></i>
client -->> server: **HTTP 200** (OK)
deactivate server
deactivate client
@enduml
