/'*****
License
--------------
Copyright © 2017 Bill & Melinda Gates Foundation
The Mojaloop files are made available by the Bill & Melinda Gates Foundation under the Apache License, Version 2.0 (the "License") and you may not use these files except in compliance with the License. You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, the Mojaloop files are distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Contributors
--------------
This is the official list of the Mojaloop project contributors for this file.
Names of the original copyright holders (individuals or organizations)
should be listed with a '*' in the first column. People who have
contributed from an organization can be listed under the organization
that actually holds the copyright for their contributions (see the
Gates Foundation organization for an example). Those individuals should have
their names indented and be marked with a '-'. Email address can be added
optionally within square brackets <email>.
* Gates Foundation

- Name Surname <name.surname@gatesfoundation.com>
--------------
******'/

@startuml

' define actor image
sprite $actor [25x48/16] {
  0000000000010000000000000
  0000000006CAC910000000000
  0000000095101292000000000
  0000000651000119000000000
  0000000B10000018400000000
  0000001A10000016600000000
  0000000B10000017510000000
  000000083100001A210000000
  0000000191000176110000000
  000000003A866A61100000000
  0000000000466211100000000
  0003333333334443333310000
  0088888888888888888892000
  0821111111111111111118200
  8311111111111111111111A00
  A111111111111111111111A20
  A111111111111111111111A20
  A111111111111111111111A20
  A111111111111111111111A20
  A111111111111111111111A20
  A111111111111111111111A20
  A111111111111111111111A20
  A111111111111111111111A20
  A111551111111111138111A20
  A111661111111111139111A20
  A211661111111111139111A20
  A211661111111111139111A20
  A211661111161111139111A20
  A2116611111A2111139111A20
  A2116611111A2111139111A20
  A2116611111A2111139111A20
  A7669611111A211113A666B20
  36669611111A211113A666610
  00016611111A2111139111110
  00006611111A2111139100000
  00006611111A2111139100000
  00006611111A2111139100000
  00006611111A2111139100000
  00006611111A2111139100000
  00006611111A2111139100000
  00006611111A2111139100000
  00006611111A2111139100000
  00006611111A2111139100000
  00006611111A2111139100000
  00006966666B7666679100000
  0000266666666666664100000
  0000000111111111111100000
  0000000000000000000000000
}

' declaring skinparam
skinparam sequenceMessageAlign center
skinparam shadowing false
skinparam defaultFontName Verdana
skinparam monochrome true
skinparam SequenceLifeLineBackgroundColor WhiteSmoke
skinparam SequenceLifeLineBorderColor Black
skinparam ActorFontStyle Bold
skinparam ActorFontSize 20
skinparam ParticipantFontStyle Bold
skinparam ParticipantFontSize 20
skinparam ParticipantBackgroundColor WhiteSmoke
skinparam ArrowColor Black

skinparam actor {
  Bordercolor none
  Backgroundcolor none
  shadowing false
}

skinparam participant {
  shadowing true
}

hide footbox

' declare title
' title Agent-initiated Cash-In example with received amount

' Actor Keys:
' participant - FSP(Payer/Payee) and Switch
' actor - Payee/Payer(OTC)

' declare actors
actor "<$actor>\nPayer\n(OTC)" as PayerOTC
actor "<$actor>\nPayer\n" as Payer
participant "\nPayer\nFSP" as PayerFSP
participant "\n\nSwitch" as Switch
participant "\nPayee\nFSP" as PayeeFSP
actor "<$actor>\nPayee\n" as Payee

' start flow
PayerOTC ->> Payer: I would like to Cash-in\nso that I receive 100 USD
PayerOTC <<- Payer: OK, you will receive a\nnotification from your FSP\ndisplaying the fees
Payer ->> PayerFSP: I would like Agent (Payee) to\nreceive 100 USD
activate PayerFSP
PayerFSP -> PayerFSP: Fee is 2 USD in Payer\nFSP for Cash-in,\nPayer will receive 1\nUSD in internal commission.
PayerFSP ->> Switch: **POST /quotes**\n(amountType=RECEIVE,\namount=100 USD, fees=2 USD)
activate Switch
PayerFSP <<-- Switch: **HTTP 202** (Accepted)
Switch ->> PayeeFSP: **POST /quotes**\n(amountType=RECEIVE,\namount=100 USD, fees=2 USD)
activate PayeeFSP
Switch <<-- PayeeFSP: **HTTP 202** (Accepted)
PayeeFSP -> PayeeFSP: Payee FSP decides to give\n1 USD in commission to\nPayer so that\nCash-in only costs 1 USD
PayeeFSP ->> Payee: By paying 101 USD in cash\nto Payer, you will receive\n100 USD to your account
PayeeFSP <<-- Payee: OK
Switch <<- PayeeFSP: **PUT /quotes/**<i><ID></i> \n(transferAmount=99 USD,\npayeeReceiveAmount=100 USD,\npayeeFspCommission=1 USD)
Switch -->> PayeeFSP: **HTTP 200** (OK)
deactivate PayeeFSP
PayerFSP <<- Switch: **PUT /quotes/**<i><ID></i>\n(transferAmount=99 USD,\npayeeReceiveAmount=100 USD,\npayeeFspCommission=1 USD)
PayerFSP -->> Switch: **HTTP 200** (OK)
deactivate Switch
Payer <<- PayerFSP: Payee will receive 100 USD\nand fee is 1 USD, you will receive\n1 USD in commission
deactivate PayerFSP
PayerOTC <<- Payer: You will receive 100 USD on your\naccount. Please give me 101 USD
PayerOTC ->> Payer: OK, here is 101 USD
Payer ->> PayerFSP: Perform transaction
activate PayerFSP
PayerFSP -> PayerFSP: Reserve 1 USD from Agent\ncommission to Payer account,\n100 USD from Payer account,\n99 USD to Switch account and 1\nUSD to fee account, 1 USD from\nFSP Commission to fee account
PayerFSP ->> Switch: **POST /transfers**\n(amount = 99 USD)
activate Switch
PayerFSP <<-- Switch: **HTTP 202** (Accepted)
Switch -> Switch: Reserve 99 USD from Payer FSP\naccount to Payee FSP account
Switch ->> PayeeFSP: **POST /transfers**\n(amount = 99 USD)
activate PayeeFSP
Switch <<-- PayeeFSP: **HTTP 202** (Accepted)
PayeeFSP -> PayeeFSP: Transfer 99 USD from Switch\naccount and 1 USD from\ninternal commission account\nto Payee account
PayeeFSP -> Payee: You have Cashed-in 100 USD
Switch <<- PayeeFSP: **PUT /transfers/**<i><ID></i>
Switch -->> PayeeFSP: **HTTP 200** (OK)
deactivate PayeeFSP
Switch -> Switch: Commit reserved transfer
PayerFSP <<- Switch: **PUT /transfers/**<i><ID></i>
PayerFSP -->> Switch: **HTTP 200** (OK)
deactivate Switch
PayerFSP -> PayerFSP: Commit reserved transfer
Payer <- PayerFSP: Transaction successful, you have\nsent 100 USD and received\n1 USD in commission
deactivate PayerFSP
PayerOTC <- Payer: Thank you!
@enduml
