@startuml Payer_SEND_ABORT_TransferPhase

!$simplified = true
!$hideSwitchDetail = false
!$advancedCoreConnectorFlow = true
!$senderName = "John"
!$senderLastName = ""
!$senderDOB = "1966-06-16"
!$receiverName = "Yaro"
!$receiverFirstName = "Yaro"
!$receiverMiddleName = ""
!$receiverLastName = ""
!$receiverDOB = "1966-06-16"
!$payerCurrency = "BWP"
!$payeeCurrency = "TZS"
!$payerFSPID = "PayerFSP"
!$payeeFSPID = "PayeeFSP"
!$fxpID = "FDH_FX"
!$payerMSISDN = "26787654321"
!$payeeMSISDN = "2551234567890"
!$payeeReceiveAmount = "44000"
!$payerSendAmount = "300"
!$payeeFee = "4000"
!$targetAmount = "48000"
!$fxpChargesSource = "33"
!$fxpChargesTarget = "6000"
!$fxpSourceAmount = "300"
!$fxpTargetAmount = "48000"
!$totalChargesSourceCurrency = "55"
!$totalChargesTargetCurrency = "10000"
!$conversionRequestId = "828cc75f16..."
!$conversionId = "581f68efb..."
!$homeTransactionId = "string"
!$quoteId = "382987a875..."
!$transactionId = "d9ce59d435..."
!$quotePayerExpiration = "2021-08-25T14:17:09.663+01:00"
!$quotePayeeExpiration = "2021-08-25T14:17:09.663+01:00"
!$commitRequestId = "77c9d78dc2..."
!$determiningTransferId = "d9ce59d43..."
!$transferId = "d9ce59d435..."
!$fxCondition = "GRzLaTP7DJ9t4P-a_B..."
!$condition = "HOr22-H3AfTDHrSkP..."


title Currency Conversion Transfer Phase ABORT flows
actor "$senderName" as A1
box "Payer DFSP" #LightBlue  
  participant "Payer DFSP" as D1
end box

participant "Mojaloop Switch" as S1

'box "Discovery Service" #LightYellow
'  participant "ALS Oracle" as ALS
'end box

box "FX provider"  
  participant "FXP\nConnector" as FXP
end box

box "Payee DFSP" #LightBlue   
  participant "Payee\nMojaloop\nConnector" as D2
end box

actor "$receiverName" as A2
autonumber

D1->>S1:Please confirm your part of the transfer
note left
**POST /fxTransfers**
{
  "commitRequestId": "$commitRequestId",
  "determiningTransferId": "$determiningTransferId",
  "initiatingFsp": "$payerFSPID",
  "counterPartyFsp": "$fxpID",
  "amountType": "SEND",
  "sourceAmount": {
    "currency": "$payerCurrency",
    "amount": "$fxpSourceAmount"},
  "targetAmount": {
    "currency": "$payeeCurrency",
    "amount": "$fxpTargetAmount"},
  "condition": "$fxCondition"
}
end note
activate S1
!if ($simplified != true)
S1-->>D1:202 I'll get back to you
!endif
deactivate D2
!if ($hideSwitchDetail != true)
S1->S1:OK, so this is an FX confirmation.
S1->S1: Is there any transfer with determiningTransactionId?\nNo, it does'nt.
!endif
S1->S1: Liquidity check and reserve on Payer DFSP's account
!if ($hideSwitchDetail != true)
note over S1
Reservations:

**$payerFSPID has a reservation of $fxpSourceAmount $payerCurrency**
end note
!endif
S1->>FXP:Please confirm the currency\n conversion part of the transfer\n **POST /fxTransfers**
deactivate S1
activate FXP
!if ($simplified != true)
FXP-->>S1:202 I'll get back to you
!endif
alt conversion failed
  FXP->>S1:Failed.
  note right
  **PUT /fxTransfers/$commitRequestId**/error
  {
    "errorInformation": {
      "errorCode": "5100",
      "errorDescription": "error message"}
  }
  ( **or** )
  **PUT /fxTransfers/$commitRequestId**
  {
    "conversionState": "ABORTED",
    "extensionList": {"extension": [{"key": "reason","value": "some reason"}]}
  }
  end note
else conversion success
  FXP->FXP:Reserve funds for FX conversion
  FXP->>S1:Confirmed. Here's the fulfilment
  note right
  **PUT /fxTransfers/$commitRequestId**
  {
    "fulfilment": "188909ceb6cd5...",
    "completedTimestamp": "2021-08-25T14:17:08.175+01:00",
    "conversionState": "RESERVED"
  }
  end note
  deactivate FXP
  S1->S1:Check fulfilment matches and cancel if not.
  alt Conversion failed
      S1->FXP:Sorry. Conversion failed
      note left
      **PATCH /fxTransfers/$commitRequestId**
      {
        "completedTimestamp": "2021-08-25T14:17:08.175+01:00",
        "conversionState": "ABORTED"
      }
      end note
      activate FXP
      FXP-->S1:Acknowledged
      FXP->FXP:Remove any reservations or obligations
      deactivate FXP
  end
end
!if ($simplified != true)
S1-->>FXP:200 Gotcha
!endif
deactivate FXP

alt Conversion failed
  S1->S1: Abort the fxTransfer. Revert \nthe position changes involved in this\n fxTransfer.
  note over S1
   **Note:**
   Incase of payee side conversion, there will be dependent transfer. 
   But do not cancel that transfer as DFSP can try currency conversion with 
   another FXP. But make sure that while processing the fulfilment of the original 
   transfer, it shouldn't pickup this fxTransfer as the dependent transfer. 
   (Maybe by removing the entry from watchlist)
  end note 
  S1->>D1:Sorry. Conversion failed
  note right
  **PUT /fxTransfers/$commitRequestId/error**
  {
    "errorInformation": {
      "errorCode": "5100",
      "errorDescription": "error message"}
  }
  ( **or** )
  **PUT /fxTransfers/$commitRequestId**
  {
    "conversionState": "ABORTED",
    "extensionList": {"extension": [{"key": "reason","value": "some reason"}]}
  }
  end note
else Conversion succeeded
    S1->D1:Conversion succeeded subject to\n transfer success\n**PUT /fxTransfers/77c9d78dc26a...**
   activate D1
end

!if ($simplified != true)
D1-->S1:200 Gotcha
!endif
D1->D1:OK, so that's all right\nNow I can send the transfer itself

D1->S1:Please do the transfer\n **POST /transfers**
deactivate D1
!if ($simplified != true)
note over D1
**POST /transfers**
{
  "transferId": "$transferId",
  "payeeFsp": "$payeeFSPID",
  "payerFsp": "$payerFSPID",
  "amount": {
   "currency": "$payeeCurrency",
   "amount": "$targetAmount"},
  "ilpPacket": "<Encoded transaction object>",
  "condition": "$condition",
  "expiration": "2016-05-24T08:38:08.699-04:00"
}
end note
!endif
activate S1
!if ($simplified != true)
S1-->D1:202 I'll get back to you
!endif
deactivate D1
!if ($hideSwitchDetail != true)
S1->S1:Is there a dependent transfer? Yes
!endif
S1->S1:Perform liquidity check and reserve funds\nagainst creditor party to dependent transfer
note over S1
Reservations:

$payerFSPID has a reservation of $fxpSourceAmount $payerCurrency
**$fxpID has a reservation of $targetAmount $payeeCurrency**
end note

S1->D2:Please do the transfer\n**POST /transfers**
deactivate S1
activate D2
!if ($simplified != true)
D2-->S1:202 I'll get back to you
!endif
D2->D2:Let me check that the terms \nof the dependent transfer are \nthe same as the ones I agreed\n to and that the fulfilment and \ncondition match

D2->A2: Hi $receiverName's, you got inbound \ntransfer $payeeReceiveAmount $payeeCurrency
deactivate D2

alt transfer failed
  D2->>S1:Transfer is rejected
  note right
  **PUT /transfers/$commitRequestId**/error
  {
    "errorInformation": {
      "errorCode": "5100",
      "errorDescription": "error message"}
  }
  ( **or** )
  {
    "transferState": "ABORETED"
  }
  end note

  activate S1
  !if ($simplified != true)
  S1-->>D2:200 Gotcha
  !endif
  
  S1->S1: Revert the position changes \ninvolved in this transfer
  S1->S1: If there are dependency fxTransfers,\n abort the fxTransfers as well and \nrevert the position changes involved \nin those fxTransfers

  S1->>FXP: The linked transfer is failed.\nRemove any reservations or obligations
  note left
  **PATCH /fxTransfers/$commitRequestId**
  {
      "completedTimestamp": "2021-08-25T14:17:08.227+01:00",
      "transferState": "ABORTED"
  }
  end note
  activate FXP
  FXP->FXP: Oops!
  FXP-->>S1:200 Gotcha
  deactivate FXP
  S1->>D1:Transfer is complete\n**PUT /transfers/$commitRequestId/error**
  activate D1
  !if ($simplified != true)
  D1-->S1:200 Gotcha
  !endif
  deactivate S1
  D1->A1:Your transfer is failed
  deactivate D1
else transfer success
  D2->>S1:Transfer is confirmed, here's the fulfilment
  note right
  **PUT /transfers/$commitRequestId**
  {
      "completedTimestamp": "2021-08-25T14:17:08.227+01:00",
      "fulfilment": "mhPUT9ZAwd...",
      "transferState": "COMMITTED"
  }
  end note
  activate S1
  !if ($simplified != true)
  S1-->>D2:200 Gotcha
  !endif
  
  !if ($hideSwitchDetail != true)
  S1->S1:Is there a dependent transfer?\nYes, there is.
  S1->S1:Is this dependency against the\n debtor party to the transfer?\nYes, it is.
  S1->S1:Create an obligation from the \ndebtor party to the party named \nin the dependency (the FXP)
  S1->S1:Is the transfer denominated in \nthe currency of the payee receive\n amount?\nYes, it is.
  S1->S1:Create an obligation from the \nparty named in the dependency\nto the creditor party for the transfer
  !else
  S1->S1:Create obligations from the payer to the FXP and from FXP to the payee
  !endif
  S1->>FXP:The transfer succeeded.\nYou can clear it in your ledgers
  note left
  **PATCH /fxTransfers/$commitRequestId**
  {
      "completedTimestamp": "2021-08-25T14:17:08.227+01:00",
      "fulfilment": "mhPUT9ZAwd...",
      "transferState": "COMMITTED"
  }
  end note
  activate FXP
  FXP->FXP:Let's just check: does this match the stuff I sent?
  FXP->FXP:It does. Great. I'll clear the conversion
  FXP-->>S1:200 Gotcha
  deactivate FXP
  note over S1
      **Ledger positions:**
      $payerFSPID has a debit of $fxpSourceAmount $payerCurrency
      $fxpID has a credit of $fxpSourceAmount $payerCurrency
      $fxpID has a debit of $fxpTargetAmount $payeeCurrency
      $payeeFSPID has a credit of $targetAmount $payeeCurrency
  end note
  S1->>D1:Transfer is complete\n**PUT /transfers/$commitRequestId**
  activate D1
  !if ($simplified != true)
  D1-->S1:200 Gotcha
  !endif
  deactivate S1

  D1->A1:Your transfer is successful
  deactivate D1
end

@enduml