/'*****
 License
 --------------
 Copyright © 2017 Bill & Melinda Gates Foundation
 The Mojaloop files are made available by the Bill & Melinda Gates Foundation under the Apache License, Version 2.0 (the "License") and you may not use these files except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, the Mojaloop files are distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
 Contributors
 --------------
 This is the official list of the Mojaloop project contributors for this file.
 Names of the original copyright holders (individuals or organizations)
 should be listed with a '*' in the first column. People who have
 contributed from an organization can be listed under the organization
 that actually holds the copyright for their contributions (see the
 Gates Foundation organization for an example). Those individuals should have
 their names indented and be marked with a '-'. Email address can be added
 optionally within square brackets <email>.
 * Gates Foundation
 - Name Surname <name.surname@gatesfoundation.com>

 * Georgi Georgiev <georgi.georgiev@modusbox.com>
 * Miguel de Barros <miguel.debarros@modusbox.com>
 * Shashikant Hirugade <shashikant.hirugade@modusbox.com>
 --------------
 ******'/

@startuml
' declate title
title 1.1.4.a. Envoyer une notification au participant (payeur/bénéficiaire) (message unique)

autonumber

' Actor Keys:
'   actor - Payer DFSP, Payee DFSP
'   boundary - APIs/Interfaces, etc
'   collections - Kafka Topics
'   control - Kafka Consumers
'   entity - Database Access Objects
'   database - Database Persistance Store

' declare actors
actor "Payer DFSP\nParticipant" as PAYER_DFSP
actor "Payee DFSP\nParticipant" as PAYEE_DFSP
control "Gestionnaire d'événements de notification ML API" as NOTIFY_HANDLER
boundary "API du service central" as CSAPI
collections "Rubrique de notification" as TOPIC_NOTIFICATIONS
collections "Rubrique d'événements" as TOPIC_EVENTS
entity "DAO participant" as PARTICIPANT_DAO
database "Stockage central" as DB

box "Financial Service Provider (Payer)" #lightGray
	participant PAYER_DFSP
end box

box "Service adaptateur ML API" #LightBlue
	participant NOTIFY_HANDLER
end box

box "Service central" #LightYellow
    participant TOPIC_NOTIFICATIONS
    participant CSAPI
    participant TOPIC_EVENTS
    participant PARTICIPANT_DAO
    participant DB
end box

box "Financial Service Provider (Payee)" #lightGray
	participant PAYEE_DFSP
end box

' start flow
activate NOTIFY_HANDLER
group Envoyer une notification aux participants
    TOPIC_NOTIFICATIONS <- NOTIFY_HANDLER: Consommer l'événement de notification
    activate TOPIC_NOTIFICATIONS
    deactivate TOPIC_NOTIFICATIONS

    group Persister les informations d'événement
        NOTIFY_HANDLER -> CSAPI: Demande de persister les informations d'événement — POST — /events
        activate CSAPI
        CSAPI -> TOPIC_EVENTS: Publier les informations d'événement
        activate TOPIC_EVENTS
        |||
        ref over TOPIC_EVENTS :  Consommation du gestionnaire d'événements\n
        |||
        TOPIC_EVENTS --> CSAPI: Renvoyer le succès
        deactivate TOPIC_EVENTS
        CSAPI --> NOTIFY_HANDLER: Renvoyer le succès
        deactivate CSAPI
    end
    note right of NOTIFY_HANDLER #lightgray
        Les détails de l'endpoint sont mis en cache ; à l'expiration du cache,
        les détails sont récupérés à nouveau
    end note
    NOTIFY_HANDLER -> CSAPI: Demander les détails de l'endpoint du participant - GET - /participants/{{fsp}}/endpoints\n<color #FF0000><b>Code d'erreur :</b> 2003</color>

    activate CSAPI
    CSAPI -> PARTICIPANT_DAO: Récupérer les détails de l'endpoint du participant\n<color #FF0000><b>Code d'erreur :</b> 2003</color>
    activate PARTICIPANT_DAO
    PARTICIPANT_DAO -> DB: Récupérer les détails de l'endpoint du participant
    activate DB
    hnote over DB #lightyellow
        participantEndpoint
    end note
    DB -> PARTICIPANT_DAO: Détails de l'endpoint du participant récupérés
    deactivate DB
    PARTICIPANT_DAO --> CSAPI: Renvoyer les détails de l'endpoint du participant
    deactivate PARTICIPANT_DAO
    CSAPI --> NOTIFY_HANDLER: Renvoyer les détails de l'endpoint du participant\n<color #FF0000><b>Codes d'erreur :</b> 3202, 3203</color>
    deactivate CSAPI
    NOTIFY_HANDLER -> PAYER_DFSP: Notification avec résultat/erreur de préparation/exécution \nau DFSP payeur sur l'endpoint spécifié - PUT \n<color #FF0000><b>Code d'erreur :</b> 1001</color>
    NOTIFY_HANDLER <-- PAYER_DFSP: HTTP 200 OK
    alt Config.SEND_TRANSFER_CONFIRMATION_TO_PAYEE === true
        NOTIFY_HANDLER -> PAYEE_DFSP: Notification avec résultat d'exécution (validé/annulé/rejeté) au DFSP bénéficiaire sur l'endpoint spécifié - PUT \n<color #FF0000><b>Code d'erreur :</b> 1001</color>
        |||
        NOTIFY_HANDLER <-- PAYEE_DFSP: HTTP 200 OK
    end
end
deactivate NOTIFY_HANDLER
@enduml
