/'*****
 License
 --------------
 Copyright © 2017 Bill & Melinda Gates Foundation
 The Mojaloop files are made available by the Bill & Melinda Gates Foundation under the Apache License, Version 2.0 (the "License") and you may not use these files except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, the Mojaloop files are distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
 Contributors
 --------------
 This is the official list of the Mojaloop project contributors for this file.
 Names of the original copyright holders (individuals or organizations)
 should be listed with a '*' in the first column. People who have
 contributed from an organization can be listed under the organization
 that actually holds the copyright for their contributions (see the
 Gates Foundation organization for an example). Those individuals should have
 their names indented and be marked with a '-'. Email address can be added
 optionally within square brackets <email>.
 * Gates Foundation
 - Name Surname <name.surname@gatesfoundation.com>

 * Georgi Georgiev <georgi.georgiev@modusbox.com>
 * Rajiv Mothilal <rajiv.mothilal@modusbox.com>
 * Miguel de Barros <miguel.debarros@modusbox.com>
 * Valentin Genev <valentin.genev@modusbox.com>
 --------------
 ******'/

@startuml
' declate title
title 1.3.2. Position Fulfil Domain v1.1

autonumber

' Actor Keys:
'   boundary - APIs/Interfaces, etc
'   collections - Kafka Topics
'   control - Kafka Consumers
'   entity - Database Access Objects
'   database - Database Persistence Store

' declare actors
control "Position Fulfil Domain" as DOMAIN_POSITION_FULFIL


' start flow
activate DOMAIN_POSITION_FULFIL
rnote right of DOMAIN_POSITION_FULFIL #lightblue
    INPUT: bin, accumulatedPosition, transferStateChanges
end note
group Fulfil Position Batch Processing
    DOMAIN_POSITION_FULFIL -> DOMAIN_POSITION_FULFIL: **runningPosition** = accumulatedPosition
    loop for each message in the bin
        DOMAIN_POSITION_FULFIL -> DOMAIN_POSITION_FULFIL: Validate current state (transferState is 'RECEIVED-FULFIL')\n<color #FF0000><b>Error code:</b> 2001</color> against failing transfers\nBatch is not rejected as a whole
        DOMAIN_POSITION_FULFIL -> DOMAIN_POSITION_FULFIL: **runningPosition** = runningPosition - payload.amount.amount
        DOMAIN_POSITION_FULFIL -> DOMAIN_POSITION_FULFIL: transferStateChange should be populated and add to **transferStateChanges**
        hnote right of DOMAIN_POSITION_FULFIL #lightyellow
            **transferStateChange**: {
                **transferStateId**: 'COMMITTED'
            }
        end note
        DOMAIN_POSITION_FULFIL -> DOMAIN_POSITION_FULFIL: participantPositionChange should be populated and add to **participantPositionChanges**
        hnote right of DOMAIN_POSITION_FULFIL #lightyellow
            **participantPositionChange**: {
                transferStateChangeId: We need this, may be need to update in the handler (???)
                value = runningPosition,
                reservedValue = participantPosition.reservedValue (???)
                createdDate = new Date() (Get time here or while executing the query in handler ???)
            }
        end note
    end
    DOMAIN_POSITION_FULFIL -> DOMAIN_POSITION_FULFIL: Return the following
    rnote right of DOMAIN_POSITION_FULFIL #lightblue
    {
        **accumulatedPosition**: runningPosition,
        **transferStateChanges**,
        **participantPositionChanges**,

        Message:
        {
            id: <transferMessage.transferId>
            from: <transferMessage.payerFsp>,
            to: <transferMessage.payeeFsp>,
            type: application/json
            content: {
                headers: <transferHeaders>,
                payload: <transferMessage>
            },
            metadata: {
                event: {
                    id: <uuid>,
                    responseTo: <previous.uuid>,
                    type: transfer,
                    action: commit || reserve,
                    createdAt: <timestamp>,
                    state: {
                        status: "success",
                        code: 0
                    }
                }
            }
        }
    end note
end
deactivate DOMAIN_POSITION_FULFIL
@enduml
