/'*****
 License
 --------------
 Copyright © 2017 Bill & Melinda Gates Foundation
 The Mojaloop files are made available by the Bill & Melinda Gates Foundation under the Apache License, Version 2.0 (the "License") and you may not use these files except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, the Mojaloop files are distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
 Contributors
 --------------
 This is the official list of the Mojaloop project contributors for this file.
 Names of the original copyright holders (individuals or organizations)
 should be listed with a '*' in the first column. People who have
 contributed from an organization can be listed under the organization
 that actually holds the copyright for their contributions (see the
 Gates Foundation organization for an example). Those individuals should have
 their names indented and be marked with a '-'. Email address can be added
 optionally within square brackets <email>.
 * Gates Foundation
 - Name Surname <name.surname@gatesfoundation.com>

 * Sam Kummary <sam@modusbox.com>
 --------------
 ******'/


@startuml
Title Transaction Requests Service
participant "Payer FSP"
participant "Switch\ntransaction-requests-service" as Switch
participant "Payee FSP"

autonumber
"Payee FSP" -\ "Payee FSP": Lookup process\n(not shown here)
note over "Payee FSP", Switch: Payee FSP generates a transaction-request to the Payer FSP
"Payee FSP" -\ Switch: POST /transactionRequests
Switch -> Switch: Validate POST /transactionRequests schema
Switch --/ "Payee FSP": 202 Accepted

alt transaction-request is valid
    
    Switch -> Switch: Validate POST /transactionRequests (internal validation)
    Switch -> Switch: Retrieve corresponding end-points for Payer FSP
    note over Switch, "Payer FSP": Switch forwards POST /transactionRequests request to Payer FSP
    Switch -\ "Payer FSP": POST /transactionRequests
    "Payer FSP" --/ Switch: 202 Accepted
    "Payer FSP" -> "Payer FSP": Process transaction-request
    
    alt Payer FSP successfully processes transaction-request
    
        note over "Payer FSP", Switch: Payer FSP responds to POST /transactionRequests
        "Payer FSP" -\ Switch: PUT /transactionRequests/{ID}
        Switch --/ "Payer FSP": 200 Ok
        
        Switch -> Switch: Validate PUT /transactionRequests/{ID}
        
        alt response is ok
        
            note over Switch, "Payee FSP": Switch forwards transaction-request response to Payee FSP
            Switch -> Switch: Retrieve corresponding end-points for Payee FSP
            
            Switch -\ "Payee FSP": PUT /transactionRequests/{ID}
            "Payee FSP" --/ Switch: 200 Ok
            
            note over "Payee FSP" #3498db: Wait for a quote, transfer by Payer FSP\nor a rejected transaction-request
        else response invalid
        
            note over Switch, "Payer FSP": Switch returns error to Payer FSP
        
            Switch -\ "Payer FSP": PUT /transactionRequests/{ID}/error
            "Payer FSP" --/ Switch : 200 Ok
            
            note over Switch, "Payer FSP" #ec7063: Note that under this\nscenario the Payee FSP\nmay not receive a response
        
        end
    else Payer FSP calculation fails or rejects the request
    
        note over "Payer FSP", Switch: Payer FSP returns error to Switch
    
        "Payer FSP" -\ Switch: PUT /transactionRequests/{ID}/error
        Switch --/ "Payer FSP": 200 OK
        
        note over "Payee FSP", Switch: Switch returns error to Payee FSP
        
        Switch -\ "Payee FSP": PUT /transactionRequests/{ID}/error
        "Payee FSP" --/ Switch: 200 OK
    
    end
else transaction-request is invalid
    note over "Payee FSP", Switch: Switch returns error to Payee FSP
    Switch -\ "Payee FSP": PUT /transactionRequests/{ID}/error
    "Payee FSP" --/ Switch: 200 OK
end
@enduml
