@startuml PayeeDFSPSingleIntegrationApiOnPatchPattern
/'*****
--------------
******'/

skinparam activityFontSize 4
skinparam activityDiamondFontSize 30
skinparam activityArrowFontSize 22
skinparam defaultFontSize 22
skinparam noteFontSize 22
skinparam monochrome true
' declare title
' title PayeeDFSPSingleIntegrationApiOnPatch
' declare actors
participant "Mojaloop\nSwitch" as Switch
box "Payment Manager\nPayee DFSP" #LightGrey
participant "SDK Scheme Adapter" as MC 
participant "Core\nConnector" as CC 
end box
participant "Core banking solution" as CBS
autonumber 1 1 "<b>[0]"
== Payee DFSP integration - Quote and Transfer - single AML check & transfer during PATCH ==

Switch->MC: **POST** /quotes
MC-->Switch: HTTP 202 Response
MC->CC: **POST** /quoterequest
activate MC
CC->CC: Do nothing
CC-->MC: Response
deactivate MC
MC-->Switch: **PUT** /quotes/{Id} 

Switch->Switch: Pass Quote to Payer
note left
Obtain consent to 
proceed with the transfer
Via **POST** /transfers
end note
    Switch-> Switch: Perform liquidity(NDC)check
    Switch->Switch: Reserve Funds
    Switch->MC: **POST** /transfers
    MC->CC: **POST** /transfers 
    activate MC
    CC->CC: Do Nothing 
    CC-->MC: response
    deactivate MC
    MC->MC: Generate Fulfilment
    MC-->Switch: **PUT** /transfers/{id} (TransferStatus='RESERVED', fulfullment)
    Switch-->Switch: Commit funds in DFSP ledgers

    Switch->MC: **PATCH** /transfers/{id} (TransferStatus='COMMITTED')
    MC->CC: Commit Transfer\n **PATCH** /transfers/{id} (TransferStatus='COMMITTED') 
    activate MC
    CC->CBS: Perform AML checks and transfer funds
    alt if (AML checks pass)
    CBS->CBS: Release funds to Payee 
    CBS-->CC: response
    CC-->MC: response
    else if (AML checks fail)
    CBS->CBS: Compensation action for AML failure. \n Return error response.
    CBS-->CC: response
    CC-->MC: response
    rnote left MC 
    Payee DFSP AML error checks (and other errors) result in:
    
    **Reconciliation Error**
       Payer has sent funds
       Payer DFSP has sent funds
       Hub considers that the Payee DFSP has received funds
       Payee DFSP has rejected the transaction
       Payee has not received funds
    endrnote
    end
    deactivate MC

@enduml