@startuml
Title Séquences du service de cotation
participant "DFSP payeur"
participant "Switch\nService de\ncotation" as Switch
participant "DFSP bénéficiaire"

autonumber
note over "DFSP payeur", Switch: Le DFSP payeur demande une cotation au DFSP bénéficiaire
"DFSP payeur" -\ Switch: POST /quotes
Switch --/ "DFSP payeur": 202 Accepted
Switch -> Switch: Valider la demande de cotation

alt cotation valide
    
    Switch -> Switch: Persister les données de cotation
    note over Switch, "DFSP bénéficiaire": Le Switch transmet la demande au DFSP bénéficiaire\n<Règles côté payeur> 
    Switch -\ "DFSP bénéficiaire": POST /quotes
    "DFSP bénéficiaire" --/ Switch: 202 Accepted
    "DFSP bénéficiaire" -> "DFSP bénéficiaire": Calculer frais et commissions
    
    alt le DFSP bénéficiaire calcule la cotation avec succès
    
        note over "DFSP bénéficiaire", Switch: Le DFSP bénéficiaire répond à la demande de cotation
        "DFSP bénéficiaire" -\ Switch: PUT /quotes/{ID}
        Switch --/ "DFSP bénéficiaire": 200 Ok
        
        Switch -> Switch: Valider la réponse de cotation
        
        alt réponse valide
        
            Switch -> Switch: Persister les données de réponse
            
            note over Switch, "DFSP payeur": Le Switch transmet la réponse au DFSP payeur\n<Règle bénéficiaire — requête complète>
            
            Switch -\ "DFSP payeur": PUT /quotes/{ID}
            "DFSP payeur" --/ Switch: 200 Ok
            
            note over "DFSP payeur" #3498db: Le DFSP payeur poursuit\nle transfert si la cotation\nest acceptable…
        else réponse invalide
        
            note over Switch, "DFSP bénéficiaire": Le Switch renvoie une erreur au DFSP bénéficiaire
        
            Switch -\ "DFSP bénéficiaire": PUT /quotes/{ID}/error
            "DFSP bénéficiaire" --/ Switch : 200 Ok
            
            note over Switch, "DFSP bénéficiaire" #ec7063: Dans ce scénario, le DFSP payeur\npeut ne pas recevoir de réponse
        
        end
    else échec du calcul ou rejet par le DFSP bénéficiaire
    
        note over "DFSP bénéficiaire", Switch: Le DFSP bénéficiaire renvoie une erreur au Switch
    
        "DFSP bénéficiaire" -\ Switch: PUT /quotes/{ID}/error
        Switch --/ "DFSP bénéficiaire": 200 OK
        Switch -> Switch: Persister les données d’erreur
        
        note over "DFSP payeur", Switch: Le Switch renvoie une erreur au DFSP payeur
        
        Switch -\ "DFSP payeur": PUT /quotes/{ID}/error
        "DFSP payeur" --/ Switch: 200 OK
    
    end
else cotation invalide
    note over "DFSP payeur", Switch: Le Switch renvoie une erreur au DFSP payeur
    Switch -\ "DFSP payeur": PUT /quotes/{ID}/error
    "DFSP payeur" --/ Switch: 200 OK
end
@enduml
