@startuml Interscheme-Agreement

title Inter-schéma — accord


participant "DFSP payeur" as payerDFSP
box Schéma A #LightBlue
  participant "Mojaloop\nSchéma A" as schemeA
  participant "Cache proxy\nSchéma A" as pc_A
end box
participant "Proxy AB" as xnp
box Schéma B #d1e0c3
  participant "Mojaloop\nSchéma B" as schemeB
  participant "Cache proxy\nSchéma B" as pc_B
end box
participant "DFSP bénéficiaire" as payeeDFSP

autonumber 1 "<b>[0]"

payerDFSP ->> schemeA: POST /quotes
schemeA -->> payerDFSP: 202 OK
note left
en-tête
  source : payerDFSP
  destination : payeeDFSP
JWS signé par payerDFSP
end note
schemeA -> pc_A: Destination hors schéma\n Recherche du proxy pour payeeDFSP = Proxy AB
schemeA ->> xnp: POST /quotes
xnp ->> schemeB: POST /quotes\nmessage non modifié
note left
en-tête
  source : payerDFSP
  destination : payeeDFSP
  fxpiop-proxy: proxyAB
JWS signé par payerDFSP
end note
schemeB -->> xnp: 202 OK
xnp -->> schemeA: 202 OK
schemeB->>payeeDFSP: POST /quotes
payeeDFSP-->>schemeB: 202 OK
note right
Vérifie le JWS signé par payerDFSP
end note
payeeDFSP->>schemeB: PUT /quotes
note right
en-tête
  source : payeeDFSP
  destination : payerDFSP
JWS signé par payeeDFSP
end note
schemeB-->>payeeDFSP: 200 OK
schemeB -> pc_B: Destination hors schéma\n Recherche du proxy pour payerDFSP = Proxy AB
schemeB->>xnp: PUT /quotes
xnp->>schemeA: PUT /quotes\nmessage non modifié
note right
en-tête
  source : payeeDFSP
  destination : payerDFSP
  fxpiop-proxy: proxyAB
JWS signé par payeeDFSP
end note
schemeA-->>xnp: 200 OK
xnp-->>schemeB: 200 OK
schemeA->>payerDFSP: PUT /quotes
note left
Vérifie le JWS signé par payeeDFSP
end note
payerDFSP -->> schemeA: 200 OK


@enduml