// a list of from, to redirects
// Regenerate this list by modifying `link_list.txt`
// and running `_generate_js_list.sh`
var redirectMapping = [
  // For example:
  {
    // an existing url on the docs 1.0 site
    from: '/documentation/contributors-guide/frequently-asked-questions.html',
    // the new destination url to use - where this page has been moved to
    to: '/getting-started/general-faqs.html'
  },
  { from: "/mojaloop-specification/", to: "/api/" },
  { from: "/mojaloop-specification/fspiop-api/documents/Logical-Data-Model.html", to: "/api/fspiop/logical-data-model.html" },
  { from: "/mojaloop-specification/fspiop-api/documents/Generic-Transaction-Patterns.html", to: "/api/fspiop/generic-transaction-patterns.html" },
  { from: "/mojaloop-specification/fspiop-api/documents/Use-Cases.html", to: "/api/fspiop/use-cases.html" },
  { from: "/mojaloop-specification/admin-api/admin-api-specification-v1.0.html", to: "/api/administration/" },
  { from: "/mojaloop-specification/fspiop-api/documents/Scheme-Rules.html", to: "/api/fspiop/scheme-rules.html" },
  { from: "/mojaloop-specification/fspiop-api/documents/JSON-Binding-Rules.html", to: "/api/fspiop/json-binding-rules.html" },
  { from: "/mojaloop-specification/fspiop-api/documents/PKI-Best-Practices.html", to: "/api/fspiop/pki-best-practices.html" },
  { from: "/mojaloop-specification/fspiop-api/documents/Signature_v1.1.html", to: "/api/fspiop/v1.1/signature.html" },
  { from: "/mojaloop-specification/fspiop-api/documents/Encryption_v1.1.html", to: "/api/fspiop/v1.1/encryption.html" },
  { from: "/mojaloop-specification/ccb-meetings/", to: "https://github.com/mojaloop/mojaloop-specification/tree/master/ccb-meetings" },
  { from: "/mojaloop-specification/ccb-meetings/Issue-and-Decision-Log.html", to: "https://github.com/mojaloop/mojaloop-specification/issues" },
  { from: "/documentation/", to: "/" },
  { from: "/documentation/mojaloop-background/", to: "/not_found.html" },
  { from: "/documentation/mojaloop-background/core-scenarios.html", to: "/not_found.html" },
  { from: "/documentation/mojaloop-background/level-one-principles.html", to: "/not_found.html" },
  { from: "/documentation/onboarding.html", to: "/not_found.html" },
  { from: "/documentation/deployment-guide/", to: "/legacy/deployment-guide/" },
  { from: "/documentation/deployment-guide/releases.html", to: "/legacy/deployment-guide/releases.html" },
  { from: "/documentation/deployment-guide/local-setup-linux.html", to: "/legacy/deployment-guide/local-setup-linux.html" },
  { from: "/documentation/deployment-guide/local-setup-mac.html", to: "/legacy/deployment-guide/local-setup-mac.html" },
  { from: "/documentation/deployment-guide/local-setup-windows.html", to: "/legacy/deployment-guide/local-setup-windows.html" },
  { from: "/documentation/deployment-guide/deployment-troubleshooting.html", to: "/legacy/deployment-guide/deployment-troubleshooting.html" },
  { from: "/documentation/deployment-guide/upgrade-strategy-guide.html", to: "/legacy/deployment-guide/upgrade-strategy-guide.html" },
  { from: "/documentation/deployment-guide/helm-legacy-migration.html", to: "/legacy/deployment-guide/helm-legacy-migration.html" },
  { from: "/documentation/deployment-guide/helm-legacy-deployment.html", to: "/legacy/deployment-guide/helm-legacy-deployment.html" },
  { from: "/documentation/contributors-guide/", to: "/community/contributing/contributors-guide.html" },
  { from: "/documentation/contributors-guide/new-contributor-checklist.html", to: "/community/contributing/new-contributor-checklist.html" },
  { from: "/documentation/contributors-guide/code-of-conduct.html", to: "/community/contributing/code-of-conduct.html" },
  { from: "/documentation/contributors-guide/signing-the-cla.html", to: "/community/contributing/signing-the-cla.html" },
  { from: "/documentation/contributors-guide/standards/", to: "/community/standards/guide.html" },
  { from: "/documentation/contributors-guide/standards/versioning.html", to: "/community/standards/versioning.html" },
  { from: "/documentation/contributors-guide/standards/creating-new-features.html", to: "/community/standards/creating-new-features.html" },
  { from: "/documentation/contributors-guide/standards/triaging-ml-oss-bugs.html", to: "/community/standards/triaging-bugs.html" },
  { from: "/documentation/contributors-guide/tools-and-technologies/", to: "/community/tools/tools-and-technologies.html" },
  { from: "/documentation/contributors-guide/tools-and-technologies/pragmatic-rest.html", to: "/community/tools/pragmatic-rest.html" },
  { from: "/documentation/contributors-guide/tools-and-technologies/code-quality-metrics.html", to: "/community/tools/code-quality-metrics.html" },
  { from: "/documentation/contributors-guide/tools-and-technologies/automated-testing.html", to: "/community/tools/automated-testing.html" },
  { from: "/documentation/contributors-guide/documentation/", to: "/community/documentation/standards.html" },
  { from: "/documentation/contributors-guide/documentation/api-documentation.html", to: "/community/documentation/api-documentation.html" },
  { from: "/documentation/contributors-guide/documentation/documentation-style-guide.html", to: "/community/documentation/style-guide.html" },
  { from: "/documentation/mojaloop-roadmap.html", to: "/community/mojaloop-roadmap.html" },
  { from: "/documentation/mojaloop-publications.html", to: "/community/mojaloop-publications.html" },
  { from: "/documentation/discussions/readme.html", to: "/community/archive/discussion-docs/" },
  { from: "/documentation/discussions/ISO_Integration.html", to: "/community/archive/discussion-docs/" },
  { from: "/documentation/discussions/decimal.html", to: "/community/archive/discussion-docs/" },
  { from: "/documentation/discussions/workbench.html", to: "/community/archive/discussion-docs/" },
  { from: "/documentation/discussions/cross_border_day_1.html", to: "/community/archive/discussion-docs/" },
  { from: "/documentation/discussions/cross_border_day_2.html", to: "/community/archive/discussion-docs/" },
  { from: "/documentation/meeting-notes/readme.html", to: "/not_found.html" },
  { from: "/documentation/meeting-notes/scrum-of-scrum-notes.html", to: "/not_found.html" },
  { from: "/documentation/meeting-notes/da-notes.html", to: "/not_found.html" },
  { from: "/documentation/meeting-notes/ccb-notes.html", to: "/not_found.html" },
  { from: "/documentation/quality-security/readme.html", to: "/legacy/quality-security/readme.html" },
  { from: "/documentation/quality-security/program-management/readme.html", to: "/legacy/quality-security/program-management/readme.html" },
  { from: "/documentation/quality-security/program-management/vulnerability-disclosure-procedure.html", to: "/legacy/quality-security/program-management/vulnerability-disclosure-procedure.html" },
  { from: "/documentation/quality-security/program-management/scheme-rules-guidelines.html", to: "/legacy/quality-security/program-management/scheme-rules-guidelines.html" },
  { from: "/documentation/quality-security/standards-guidelines/readme.html", to: "/legacy/quality-security/standards-guidelines/readme.html" },
  { from: "/documentation/quality-security/reference-implementation.html", to: "/legacy/quality-security/reference-implementation.html" },
  { from: "/documentation/api/", to: "/api/" },
  { from: "/documentation/api/central-ledger-api-specification.html", to: "/api/administration/" },
  { from: "/documentation/api/central-settlements-api-specification.html", to: "/api/settlement/" },
  { from: "/documentation/api/als-oracle-api-specification.html", to: "/legacy/api/als-oracle-api-specification.html" },
  { from: "/documentation/mojaloop-technical-overview/", to: "/legacy/mojaloop-technical-overview/" },
  { from: "/documentation/mojaloop-technical-overview/overview/", to: "/legacy/mojaloop-technical-overview/overview/" },
  { from: "/documentation/mojaloop-technical-overview/overview/components-PI14.html", to: "/legacy/mojaloop-technical-overview/overview/components-PI14.html" },
  { from: "/documentation/mojaloop-technical-overview/overview/components-PI12.html", to: "/legacy/mojaloop-technical-overview/overview/components-PI12.html" },
  { from: "/documentation/mojaloop-technical-overview/overview/components-PI11.html", to: "/legacy/mojaloop-technical-overview/overview/components-PI11.html" },
  { from: "/documentation/mojaloop-technical-overview/overview/components-PI8.html", to: "/legacy/mojaloop-technical-overview/overview/components-PI8.html" },
  { from: "/documentation/mojaloop-technical-overview/overview/components-PI7.html", to: "/legacy/mojaloop-technical-overview/overview/components-PI7.html" },
  { from: "/documentation/mojaloop-technical-overview/overview/components-PI6.html", to: "/legacy/mojaloop-technical-overview/overview/components-PI6.html" },
  { from: "/documentation/mojaloop-technical-overview/overview/components-PI5.html", to: "/legacy/mojaloop-technical-overview/overview/components-PI5.html" },
  { from: "/documentation/mojaloop-technical-overview/overview/components-PI3.html", to: "/legacy/mojaloop-technical-overview/overview/components-PI3.html" },
  { from: "/documentation/mojaloop-technical-overview/account-lookup-service/", to: "/legacy/mojaloop-technical-overview/account-lookup-service/" },
  { from: "/documentation/mojaloop-technical-overview/account-lookup-service/als-get-participants.html", to: "/legacy/mojaloop-technical-overview/account-lookup-service/als-get-participants.html" },
  { from: "/documentation/mojaloop-technical-overview/account-lookup-service/als-post-participants.html", to: "/legacy/mojaloop-technical-overview/account-lookup-service/als-post-participants.html" },
  { from: "/documentation/mojaloop-technical-overview/account-lookup-service/als-post-participants-batch.html", to: "/legacy/mojaloop-technical-overview/account-lookup-service/als-post-participants-batch.html" },
  { from: "/documentation/mojaloop-technical-overview/account-lookup-service/als-del-participants.html", to: "/legacy/mojaloop-technical-overview/account-lookup-service/als-del-participants.html" },
  { from: "/documentation/mojaloop-technical-overview/account-lookup-service/als-get-parties.html", to: "/legacy/mojaloop-technical-overview/account-lookup-service/als-get-parties.html" },
  { from: "/documentation/mojaloop-technical-overview/quoting-service/", to: "/legacy/mojaloop-technical-overview/quoting-service/" },
  { from: "/documentation/mojaloop-technical-overview/quoting-service/qs-get-quotes.html", to: "/legacy/mojaloop-technical-overview/quoting-service/qs-get-quotes.html" },
  { from: "/documentation/mojaloop-technical-overview/quoting-service/qs-post-quotes.html", to: "/legacy/mojaloop-technical-overview/quoting-service/qs-post-quotes.html" },
  { from: "/documentation/mojaloop-technical-overview/quoting-service/qs-get-bulk-quotes.html", to: "/legacy/mojaloop-technical-overview/quoting-service/qs-get-bulk-quotes.html" },
  { from: "/documentation/mojaloop-technical-overview/quoting-service/qs-post-bulk-quotes.html", to: "/legacy/mojaloop-technical-overview/quoting-service/qs-post-bulk-quotes.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/", to: "/legacy/mojaloop-technical-overview/central-ledger/" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/admin-operations/", to: "/legacy/mojaloop-technical-overview/central-ledger/admin-operations/" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/admin-operations/1.0.0-post-participant-position-limit.html", to: "/legacy/mojaloop-technical-overview/central-ledger/admin-operations/1.0.0-post-participant-position-limit.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/admin-operations/1.1.0-get-participant-limit-details.html", to: "/legacy/mojaloop-technical-overview/central-ledger/admin-operations/1.1.0-get-participant-limit-details.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/admin-operations/1.0.0-get-limits-for-all-participants.html", to: "/legacy/mojaloop-technical-overview/central-ledger/admin-operations/1.0.0-get-limits-for-all-participants.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/admin-operations/1.1.0-post-participant-limits.html", to: "/legacy/mojaloop-technical-overview/central-ledger/admin-operations/1.1.0-post-participant-limits.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/admin-operations/1.1.5-get-transfer-status.html", to: "/legacy/mojaloop-technical-overview/central-ledger/admin-operations/1.1.5-get-transfer-status.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/admin-operations/3.1.0-post-participant-callback-details.html", to: "/legacy/mojaloop-technical-overview/central-ledger/admin-operations/3.1.0-post-participant-callback-details.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/admin-operations/3.1.0-get-participant-callback-details.html", to: "/legacy/mojaloop-technical-overview/central-ledger/admin-operations/3.1.0-get-participant-callback-details.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/admin-operations/4.1.0-get-participant-position-details.html", to: "/legacy/mojaloop-technical-overview/central-ledger/admin-operations/4.1.0-get-participant-position-details.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/admin-operations/4.2.0-get-positions-of-all-participants.html", to: "/legacy/mojaloop-technical-overview/central-ledger/admin-operations/4.2.0-get-positions-of-all-participants.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/1.1.0-prepare-transfer-request.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/1.1.0-prepare-transfer-request.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/1.1.1.a-prepare-handler-consume.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/1.1.1.a-prepare-handler-consume.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/1.3.0-position-handler-consume.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/1.3.0-position-handler-consume.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/1.3.0-position-handler-consume-v1.1.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/1.3.0-position-handler-consume-v1.1.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/1.3.1-prepare-position-handler-consume.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/1.3.1-prepare-position-handler-consume.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/1.1.2.a-position-handler-consume.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/1.1.2.a-position-handler-consume.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/2.1.0-fulfil-transfer-request.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/2.1.0-fulfil-transfer-request.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/2.1.0-fulfil-transfer-request-v1.1.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/2.1.0-fulfil-transfer-request-v1.1.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/2.1.1-fulfil-handler-consume.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/2.1.1-fulfil-handler-consume.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/2.1.1-fulfil-handler-consume-v1.1.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/2.1.1-fulfil-handler-consume-v1.1.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/1.3.2-fulfil-position-handler-consume.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/1.3.2-fulfil-position-handler-consume.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/1.3.2-fulfil-position-handler-consume-v1.1.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/1.3.2-fulfil-position-handler-consume-v1.1.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/2.2.0-fulfil-reject-transfer.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/2.2.0-fulfil-reject-transfer.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/2.2.0.a-fulfil-abort-transfer.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/2.2.0.a-fulfil-abort-transfer.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/2.2.1-fulfil-reject-handler.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/2.2.1-fulfil-reject-handler.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/2.2.0-fulfil-reject-transfer-v1.1.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/2.2.0-fulfil-reject-transfer-v1.1.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/2.2.0.a-fulfil-abort-transfer-v1.1.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/2.2.0.a-fulfil-abort-transfer-v1.1.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/2.2.1-fulfil-reject-handler-v1.1.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/2.2.1-fulfil-reject-handler-v1.1.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/1.1.4.a-send-notification-to-participant.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/1.1.4.a-send-notification-to-participant.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/1.1.4.a-send-notification-to-participant-v1.1.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/1.1.4.a-send-notification-to-participant-v1.1.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/1.1.4.b-send-notification-to-participant.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/1.1.4.b-send-notification-to-participant.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/1.3.3-abort-position-handler-consume.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/1.3.3-abort-position-handler-consume.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/2.3.0-transfer-timeout.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/2.3.0-transfer-timeout.html" },
  { from: "/documentation/mojaloop-technical-overview/central-ledger/transfers/2.3.1-timeout-handler-consume.html", to: "/legacy/mojaloop-technical-overview/central-ledger/transfers/2.3.1-timeout-handler-consume.html" },
  { from: "/documentation/mojaloop-technical-overview/central-bulk-transfers/", to: "/legacy/mojaloop-technical-overview/central-bulk-transfers/" },
  { from: "/documentation/mojaloop-technical-overview/central-bulk-transfers/transfers/1.1.0-bulk-prepare-transfer-request-overview.html", to: "/legacy/mojaloop-technical-overview/central-bulk-transfers/transfers/1.1.0-bulk-prepare-transfer-request-overview.html" },
  { from: "/documentation/mojaloop-technical-overview/central-bulk-transfers/transfers/1.1.1-bulk-prepare-handler-consume.html", to: "/legacy/mojaloop-technical-overview/central-bulk-transfers/transfers/1.1.1-bulk-prepare-handler-consume.html" },
  { from: "/documentation/mojaloop-technical-overview/central-bulk-transfers/transfers/1.2.1-prepare-handler-consume-for-bulk.html", to: "/legacy/mojaloop-technical-overview/central-bulk-transfers/transfers/1.2.1-prepare-handler-consume-for-bulk.html" },
  { from: "/documentation/mojaloop-technical-overview/central-bulk-transfers/transfers/1.3.0-position-handler-consume-overview.html", to: "/legacy/mojaloop-technical-overview/central-bulk-transfers/transfers/1.3.0-position-handler-consume-overview.html" },
  { from: "/documentation/mojaloop-technical-overview/central-bulk-transfers/transfers/1.3.1-prepare-position-handler-consume.html", to: "/legacy/mojaloop-technical-overview/central-bulk-transfers/transfers/1.3.1-prepare-position-handler-consume.html" },
  { from: "/documentation/mojaloop-technical-overview/central-bulk-transfers/transfers/2.3.1-fulfil-position-handler-consume.html", to: "/legacy/mojaloop-technical-overview/central-bulk-transfers/transfers/2.3.1-fulfil-position-handler-consume.html" },
  { from: "/documentation/mojaloop-technical-overview/central-bulk-transfers/transfers/2.3.2-position-consume-abort.html", to: "/legacy/mojaloop-technical-overview/central-bulk-transfers/transfers/2.3.2-position-consume-abort.html" },
  { from: "/documentation/mojaloop-technical-overview/central-bulk-transfers/transfers/2.1.0-bulk-fulfil-transfer-request-overview.html", to: "/legacy/mojaloop-technical-overview/central-bulk-transfers/transfers/2.1.0-bulk-fulfil-transfer-request-overview.html" },
  { from: "/documentation/mojaloop-technical-overview/central-bulk-transfers/transfers/2.1.1-bulk-fulfil-handler-consume.html", to: "/legacy/mojaloop-technical-overview/central-bulk-transfers/transfers/2.1.1-bulk-fulfil-handler-consume.html" },
  { from: "/documentation/mojaloop-technical-overview/central-bulk-transfers/transfers/2.2.1-fulfil-commit-for-bulk.html", to: "/legacy/mojaloop-technical-overview/central-bulk-transfers/transfers/2.2.1-fulfil-commit-for-bulk.html" },
  { from: "/documentation/mojaloop-technical-overview/central-bulk-transfers/transfers/2.2.2-fulfil-abort-for-bulk.html", to: "/legacy/mojaloop-technical-overview/central-bulk-transfers/transfers/2.2.2-fulfil-abort-for-bulk.html" },
  { from: "/documentation/mojaloop-technical-overview/central-bulk-transfers/transfers/1.4.1-bulk-processing-handler.html", to: "/legacy/mojaloop-technical-overview/central-bulk-transfers/transfers/1.4.1-bulk-processing-handler.html" },
  { from: "/documentation/mojaloop-technical-overview/central-bulk-transfers/transfers/3.1.0-transfer-timeout-overview-for-bulk.html", to: "/legacy/mojaloop-technical-overview/central-bulk-transfers/transfers/3.1.0-transfer-timeout-overview-for-bulk.html" },
  { from: "/documentation/mojaloop-technical-overview/central-bulk-transfers/transfers/3.1.1-transfer-timeout-handler-consume.html", to: "/legacy/mojaloop-technical-overview/central-bulk-transfers/transfers/3.1.1-transfer-timeout-handler-consume.html" },
  { from: "/documentation/mojaloop-technical-overview/central-bulk-transfers/transfers/4.1.0-transfer-abort-overview-for-bulk.html", to: "/legacy/mojaloop-technical-overview/central-bulk-transfers/transfers/4.1.0-transfer-abort-overview-for-bulk.html" },
  { from: "/documentation/mojaloop-technical-overview/central-bulk-transfers/transfers/5.1.0-transfer-get-overview-for-bulk.html", to: "/legacy/mojaloop-technical-overview/central-bulk-transfers/transfers/5.1.0-transfer-get-overview-for-bulk.html" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/", to: "/legacy/mojaloop-technical-overview/central-settlements/" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/settlement-process/", to: "/legacy/mojaloop-technical-overview/central-settlements/settlement-process/" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/settlement-process/get-settlement-windows-by-params.html", to: "/legacy/mojaloop-technical-overview/central-settlements/settlement-process/get-settlement-windows-by-params.html" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/settlement-process/get-settlement-window-by-id.html", to: "/legacy/mojaloop-technical-overview/central-settlements/settlement-process/get-settlement-window-by-id.html" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/settlement-process/post-close-settlement-window.html", to: "/legacy/mojaloop-technical-overview/central-settlements/settlement-process/post-close-settlement-window.html" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/settlement-process/post-create-settlement.html", to: "/legacy/mojaloop-technical-overview/central-settlements/settlement-process/post-create-settlement.html" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/settlement-process/get-settlement-by-id.html", to: "/legacy/mojaloop-technical-overview/central-settlements/settlement-process/get-settlement-by-id.html" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/settlement-process/put-settlement-transfer-ack.html", to: "/legacy/mojaloop-technical-overview/central-settlements/settlement-process/put-settlement-transfer-ack.html" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/settlement-process/put-settlement-abort.html", to: "/legacy/mojaloop-technical-overview/central-settlements/settlement-process/put-settlement-abort.html" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/settlement-process/get-settlement-by-spa.html", to: "/legacy/mojaloop-technical-overview/central-settlements/settlement-process/get-settlement-by-spa.html" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/settlement-process/get-settlements-by-params.html", to: "/legacy/mojaloop-technical-overview/central-settlements/settlement-process/get-settlements-by-params.html" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/settlement-process/gross-settlement-handler-consume.html", to: "/legacy/mojaloop-technical-overview/central-settlements/settlement-process/gross-settlement-handler-consume.html" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/settlement-process/rules-handler-consume.html", to: "/legacy/mojaloop-technical-overview/central-settlements/settlement-process/rules-handler-consume.html" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/funds-in-out/", to: "/legacy/mojaloop-technical-overview/central-settlements/funds-in-out/" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/funds-in-out/reconciliation-transfer-prepare.html", to: "/legacy/mojaloop-technical-overview/central-settlements/funds-in-out/reconciliation-transfer-prepare.html" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/funds-in-out/transfer-state-and-position-change.html", to: "/legacy/mojaloop-technical-overview/central-settlements/funds-in-out/transfer-state-and-position-change.html" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/funds-in-out/funds-in-prepare-reserve-commit.html", to: "/legacy/mojaloop-technical-overview/central-settlements/funds-in-out/funds-in-prepare-reserve-commit.html" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/funds-in-out/funds-out-prepare-reserve.html", to: "/legacy/mojaloop-technical-overview/central-settlements/funds-in-out/funds-out-prepare-reserve.html" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/funds-in-out/funds-out-commit.html", to: "/legacy/mojaloop-technical-overview/central-settlements/funds-in-out/funds-out-commit.html" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/funds-in-out/funds-out-abort.html", to: "/legacy/mojaloop-technical-overview/central-settlements/funds-in-out/funds-out-abort.html" },
  { from: "/documentation/mojaloop-technical-overview/central-settlements/oss-settlement-fsd.html", to: "/legacy/mojaloop-technical-overview/central-settlements/oss-settlement-fsd.html" },
  { from: "/documentation/mojaloop-technical-overview/transaction-requests-service/", to: "/legacy/mojaloop-technical-overview/transaction-requests-service/" },
  { from: "/documentation/mojaloop-technical-overview/transaction-requests-service/transaction-requests-post.html", to: "/legacy/mojaloop-technical-overview/transaction-requests-service/transaction-requests-post.html" },
  { from: "/documentation/mojaloop-technical-overview/transaction-requests-service/transaction-requests-get.html", to: "/legacy/mojaloop-technical-overview/transaction-requests-service/transaction-requests-get.html" },
  { from: "/documentation/mojaloop-technical-overview/transaction-requests-service/authorizations.html", to: "/legacy/mojaloop-technical-overview/transaction-requests-service/authorizations.html" },
  { from: "/documentation/mojaloop-technical-overview/central-event-processor/", to: "/legacy/mojaloop-technical-overview/central-event-processor/" },
  { from: "/documentation/mojaloop-technical-overview/central-event-processor/9.1.0-event-handler-placeholder.html", to: "/legacy/mojaloop-technical-overview/central-event-processor/9.1.0-event-handler-placeholder.html" },
  { from: "/documentation/mojaloop-technical-overview/central-event-processor/5.1.1-notification-handler-for-rejections.html", to: "/legacy/mojaloop-technical-overview/central-event-processor/5.1.1-notification-handler-for-rejections.html" },
  { from: "/documentation/mojaloop-technical-overview/central-event-processor/signature-validation.html", to: "/legacy/mojaloop-technical-overview/central-event-processor/signature-validation.html" },
  { from: "/documentation/mojaloop-technical-overview/event-framework/", to: "/legacy/mojaloop-technical-overview/event-framework/" },
  { from: "/documentation/mojaloop-technical-overview/event-stream-processor/", to: "/legacy/mojaloop-technical-overview/event-stream-processor/" },
  { from: "/documentation/mojaloop-technical-overview/fraud-services/", to: "/legacy/mojaloop-technical-overview/fraud-services/" },
  { from: "/documentation/mojaloop-technical-overview/fraud-services/related-documents/documentation.html", to: "/legacy/mojaloop-technical-overview/fraud-services/related-documents/documentation.html" },
  { from: "/documentation/mojaloop-technical-overview/sdk-scheme-adapter/", to: "/legacy/mojaloop-technical-overview/sdk-scheme-adapter/" },
  { from: "/documentation/mojaloop-technical-overview/sdk-scheme-adapter/usage/", to: "/legacy/mojaloop-technical-overview/sdk-scheme-adapter/usage/" },
  { from: "/documentation/mojaloop-technical-overview/sdk-scheme-adapter/usage/scheme-adapter-to-scheme-adapter/", to: "/legacy/mojaloop-technical-overview/sdk-scheme-adapter/usage/scheme-adapter-to-scheme-adapter/" },
  { from: "/documentation/mojaloop-technical-overview/sdk-scheme-adapter/usage/scheme-adapter-and-local-k8s/", to: "/legacy/mojaloop-technical-overview/sdk-scheme-adapter/usage/scheme-adapter-and-local-k8s/" },
  { from: "/documentation/mojaloop-technical-overview/sdk-scheme-adapter/usage/scheme-adapter-and-wso2-api-gateway/", to: "/legacy/mojaloop-technical-overview/sdk-scheme-adapter/usage/scheme-adapter-and-wso2-api-gateway/" },
  { from: "/documentation/mojaloop-technical-overview/ml-testing-toolkit/", to: "/legacy/mojaloop-technical-overview/ml-testing-toolkit/" },
  { from: "/documentation/repositories/", to: "/legacy/repositories/" },
  { from: "/documentation/repositories/helm.html", to: "/legacy/repositories/helm.html" },
  { from: "/documentation/repositories/project.html", to: "/legacy/repositories/project.html" },
  { from: "/documentation/glossary.html", to: "/legacy/glossary.html" }
]

function handler(event) {
  var request = event.request;
  var uri = request.uri;
  var response

  redirectMapping.forEach(m => {
    if (uri.endsWith(m.from)) {
      // request.uri = request.uri.replace(m.from, m.to)
      var newurl = uri.replace(m.from, m.to)
      console.log(`redirecting: ${m.from} ----> ${m.to}`)

      response = {
        statusCode: 301,
        statusDescription: 'Moved Permanently',
        headers: { "location": { "value": newurl } }
      }
    }
  })
  if (response) {
    return response
  }

  // fallthrough
  return request
}
