@startuml PAYER_SEND_Confirmation
!$simplified = true
!$hideSwitchDetail = false
!$advancedCoreConnectorFlow = true
!$senderName = "John"
!$senderLastName = ""
!$senderDOB = "1966-06-16"
!$receiverName = "Yaro"
!$receiverFirstName = "Yaro"
!$receiverMiddleName = ""
!$receiverLastName = ""
!$receiverDOB = "1966-06-16"
!$payerCurrency = "BWP"
!$payeeCurrency = "TZS"
!$payerFSPID = "PayerFSP"
!$payeeFSPID = "PayeeFSP"
!$fxpID = "FDH_FX"
!$payerMSISDN = "26787654321"
!$payeeMSISDN = "2551234567890"
!$payeeReceiveAmount = "44000"
!$payerSendAmount = "300"
!$payeeFee = "4000"
!$targetAmount = "48000"
!$fxpChargesSource = "33"
!$fxpChargesTarget = "6000"
!$fxpSourceAmount = "300"
!$fxpTargetAmount = "48000"
!$totalChargesSourceCurrency = "55"
!$totalChargesTargetCurrency = "10000"
!$conversionRequestId = "828cc75f1654415e8fcddf76cc"
!$conversionId = "581f68efb54f416f9161ac34e8"
!$homeTransactionId = "string"
!$quoteId = "382987a875ce4037b500c475e0"
!$transactionId = "d9ce59d4359843968630581bb0"
!$quotePayerExpiration = "2021-08-25T14:17:09.663+01:00"
!$quotePayeeExpiration = "2021-08-25T14:17:09.663+01:00"
!$commitRequestId = "77c9d78dc26a44748b3c99b96a"
!$determiningTransferId = "d9ce59d4359843968630581bb0"
!$transferId = "d9ce59d4359843968630581bb0"
!$fxCondition = "GRzLaTP7DJ9t4P-a_B..."
!$condition = "HOr22-H3AfTDHrSkP..."


title Le DFSP payeur présente les conditions au payeur
actor "$senderName" as A1
box "DFSP payeur" #LightBlue  
  participant "DFSP payeur" as D1
end box

'participant "Commutateur Mojaloop" as S1

'box "Service de découverte" #LightYellow
'  participant "Oracle ALS" as ALS
'end box

'box "Fournisseur de change"  
'  participant "Connecteur\nFXP" as FXP
'end box

'box "DFSP bénéficiaire" #LightBlue   
'  participant "Connecteur Mojaloop\nbénéficiaire" as D2
'end box

'actor "$receiverName" as A2
autonumber

D1->A1: Présenter les conditions du transfert au payeur
note right
Bonjour, $senderName : 
Je peux effectuer le transfert.
Cela vous coûtera $totalChargesSourceCurrency $payerCurrency ($totalChargesTargetCurrency $payeeCurrency) de frais
et $receiverName recevra $payeeReceiveAmount $payeeCurrency.
**Souhaitez-vous continuer ?**
end note
A1->D1: Parfait ! Oui, continuez s'il vous plaît

D1->D1: Le payeur a accepté les conditions — merci de poursuivre
@enduml