@startuml PAYER_SEND_Confirmation
!$simplified = true
!$hideSwitchDetail = false
!$advancedCoreConnectorFlow = true
!$senderName = "John"
!$senderLastName = ""
!$senderDOB = "1966-06-16"
!$receiverName = "Yaro"
!$receiverFirstName = "Yaro"
!$receiverMiddleName = ""
!$receiverLastName = ""
!$receiverDOB = "1966-06-16"
!$payerCurrency = "BWP"
!$payeeCurrency = "TZS"
!$payerFSPID = "PayerFSP"
!$payeeFSPID = "PayeeFSP"
!$fxpID = "FDH_FX"
!$payerMSISDN = "26787654321"
!$payeeMSISDN = "2551234567890"
!$payeeReceiveAmount = "44000"
!$payerSendAmount = "300"
!$payeeFee = "4000"
!$targetAmount = "48000"
!$fxpChargesSource = "33"
!$fxpChargesTarget = "6000"
!$fxpSourceAmount = "300"
!$fxpTargetAmount = "48000"
!$totalChargesSourceCurrency = "55"
!$totalChargesTargetCurrency = "10000"
!$conversionRequestId = "828cc75f1654415e8fcddf76cc"
!$conversionId = "581f68efb54f416f9161ac34e8"
!$homeTransactionId = "string"
!$quoteId = "382987a875ce4037b500c475e0"
!$transactionId = "d9ce59d4359843968630581bb0"
!$quotePayerExpiration = "2021-08-25T14:17:09.663+01:00"
!$quotePayeeExpiration = "2021-08-25T14:17:09.663+01:00"
!$commitRequestId = "77c9d78dc26a44748b3c99b96a"
!$determiningTransferId = "d9ce59d4359843968630581bb0"
!$transferId = "d9ce59d4359843968630581bb0"
!$fxCondition = "GRzLaTP7DJ9t4P-a_B..."
!$condition = "HOr22-H3AfTDHrSkP..."


title Payer DFSP presents the terms to the Payer
actor "$senderName" as A1
box "Payer DFSP" #LightBlue  
  participant "Payer DFSP" as D1
end box

'participant "Mojaloop Switch" as S1

'box "Discovery Service" #LightYellow
'  participant "ALS Oracle" as ALS
'end box

'box "FX provider"  
'  participant "FXP\nConnector" as FXP
'end box

'box "Payee DFSP" #LightBlue   
'  participant "Payee\nMojaloop\nConnector" as D2
'end box

'actor "$receiverName" as A2
autonumber

D1->A1: Present the terms of the transfer to the Payer
note right
Hi, $senderName: 
I can do the transfer.
It'll cost you $totalChargesSourceCurrency $payerCurrency($totalChargesTargetCurrency $payeeCurrency) in fees
and $receiverName will receive $payeeReceiveAmount $payeeCurrency.
**Let me know if you want to go ahead?**
end note
A1->D1: Great! Yes please, go ahead

D1->D1: Payer has accepted the terms please proceed
@enduml