@startuml Interscheme-Transfer

title Interscheme - Transfer

participant "Payer DFSP" as payerDFSP
box Scheme A #LightBlue
  participant "Mojaloop\nScheme A" as schemeA
  participant "Proxy Cache\nScheme A" as pc_A
end box
participant "Proxy AB" as xnp
box Scheme B #d1e0c3
  participant "Mojaloop\nScheme B" as schemeB
  participant "Proxy Cache\nScheme B" as pc_B
end box
participant "Payee DFS" as payeeDFSP

autonumber 1 "<b>[0]"

payerDFSP ->> schemeA: POST /transfers
note left
header 
  source: payerDFSP
  destination: payeeDFSP
JWS signed by payerDFSP
body 
    transferId: 1234
end note
schemeA -->> payerDFSP: 202 OK
schemeA -> schemeA: Payer DFSP\n - Checks limits\n - Updates position
schemeA -> pc_A: Destination not in Scheme\nLookup proxy for payeeDFSP = Proxy AB
schemeA ->> xnp: POST /transfers
xnp ->> schemeB: POST /transfers
note left
header 
  source: payerDFSP
  destination: payeeDFSP
  fxpiop-proxy: proxyAB
JWS signed by payerDFSP
body 
    transferId: 1234
end note
schemeB -->> xnp: 202 OK
xnp -->> schemeA: 202 OK
schemeA -> schemeA: Disable timeout

schemeB -> schemeB: Proxy AB\n **- No limit check**\n - Updates position
schemeB->>payeeDFSP: POST /transfers
note right
Checks JWS signed by payerDFSP
end note
payeeDFSP->>schemeB: PUT /transfers \n{fulfilment: "xyz", transferState: "RESERVED"}
note right
header 
  source: payeeDFSP
  destination: payerDFSP
JWS signed by payeeDFSP  
end note
schemeB -> schemeB: Payer DFSP\n - Updates position
schemeB -> pc_B: Lookup proxy for payerDFSP = Proxy AB
schemeB->>xnp: PUT /transfers
xnp->>schemeA: PUT /transfers
note right
header 
  source: payeeDFSP
  destination: payerDFSP
  fxpiop-proxy: proxyAB
JWS signed by payeeDFSP  
end note
schemeA-->>xnp: 200 OK
xnp-->>schemeB: 200 OK
schemeB->>payeeDFSP: PATCH /transfers \n{transferState: "COMMITTED"}
payeeDFSP-->>schemeB: 200 OK
schemeA -> schemeA: NX Proxy\n - Updates position
schemeA->>payerDFSP: PUT /transfers
note left
Checks JWS signed by payeeDFSP
end note
payerDFSP -->> schemeA: 200 OK

@enduml