/'*****
 License
 --------------
 Copyright © 2017 Bill & Melinda Gates Foundation
 The Mojaloop files are made available by the Bill & Melinda Gates Foundation under the Apache License, Version 2.0 (the "License") and you may not use these files except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, the Mojaloop files are distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
 Contributors
 --------------
 This is the official list of the Mojaloop project contributors for this file.
 Names of the original copyright holders (individuals or organizations)
 should be listed with a '*' in the first column. People who have
 contributed from an organization can be listed under the organization
 that actually holds the copyright for their contributions (see the
 Gates Foundation organization for an example). Those individuals should have
 their names indented and be marked with a '-'. Email address can be added
 optionally within square brackets <email>.
 * Gates Foundation
 - Name Surname <name.surname@gatesfoundation.com>

 * Georgi Georgiev <georgi.georgiev@modusbox.com>
 * Rajiv Mothilal <rajiv.mothilal@modusbox.com>
 --------------
 ******'/


@startuml
' declate title
title 7.2.1. Post Participant Details

autonumber
' Actor Keys:
' boundary - APIs/Interfaces, etc
' entity - Database Access Objects
' database - Database Persistance Store

' declare actors
actor "Payer FSP" as PAYER_FSP
boundary "Account Lookup\nService (ALS)" as ALS_API
control "ALS Participant\nHandler" as ALS_PARTICIPANT_HANDLER
entity "ALS CentralService\nEndpoint DAO" as ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO
entity "ALS CentralService\nParticipant DAO" as ALS_CENTRALSERVICE_PARTICIPANT_DAO
entity "ALS Participant\nOracle DAO" as ALS_PARTICIPANT_ORACLE_DAO
database "ALS Database" as ALS_DB
boundary "Oracle Service API" as ORACLE_API
boundary "Central Service API" as CENTRALSERVICE_API

box "Financial Service Provider" #LightGrey
participant PAYER_FSP
end box

box "Account Lookup Service" #LightYellow
participant ALS_API
participant ALS_PARTICIPANT_HANDLER
participant ALS_PARTICIPANT_ORACLE_DAO
participant ALS_DB
participant ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO
participant ALS_CENTRALSERVICE_PARTICIPANT_DAO
end box

box "Central Services" #LightGreen
participant CENTRALSERVICE_API
end box

box "ALS Oracle Service/Adapter" #LightBlue
participant ORACLE_API
end box

' START OF FLOW

group Post Participant's FSP Details
    note right of PAYER_FSP #yellow
        Headers - postParticipantsHeaders: {
            Content-Length: <Content-Length>,
            Content-Type: <Content-Type>,
            Date: <Date>,
            X-Forwarded-For: <X-Forwarded-For>,
            FSPIOP-Source: <FSPIOP-Source>,
            FSPIOP-Destination: <FSPIOP-Destination>,
            FSPIOP-Encryption: <FSPIOP-Encryption>,
            FSPIOP-Signature: <FSPIOP-Signature>,
            FSPIOP-URI: <FSPIOP-URI>,
            FSPIOP-HTTP-Method: <FSPIOP-HTTP-Method>
        }

        Payload - postParticipantsMessage:
        {
          "requestId": "string",
          "partyList": [
            {
              "partyIdType": "string",
              "partyIdentifier": "string",
              "partySubIdOrType": "string",
              "fspId": "string"
            }
          ],
          "currency": "string"
        }
    end note
    PAYER_FSP ->> ALS_API: Request to add participant's FSP details\nPOST - /participants\n<color #388724><b>Response code:</b> 202</color> \n<color #FF0000><b>Error code:</b> 200x, 300x, 310x, 320x</color>
'    hnote over ALS_API #lightyellow
'            "POST /participant" operation only supports requests which contain:
'            - All Participant's FSPs match the FSPIOP-Source
'            - All Participant's TYPEs are the same
'            - All Participant's will be of the same Currency
'    end note
    activate ALS_API
    ALS_API -> ALS_API: Validate request against\nMojaloop Interface Specification\n<color #FF0000><b>Error code:</b> 300x, 310x</color>

    ALS_API -> ALS_PARTICIPANT_HANDLER: Process create participant's FSP details
    activate ALS_PARTICIPANT_HANDLER

    '********************* Sort into Participant buckets based on {TYPE} - START ************************
    ALS_PARTICIPANT_HANDLER -> ALS_PARTICIPANT_HANDLER: Group Participant lists into a Map based on {TYPE}

    '********************* Sort into Participant buckets based on {TYPE} - END ************************

    loop for keys in ParticipantMap -> TYPE

        '********************* Fetch Oracle Routing Information - START ************************

        '********************* Retrieve Oracle Routing Information - START ************************

        ALS_PARTICIPANT_HANDLER <-> ALS_DB: Get Oracle Routing Config\n<color #FF0000><b>Error code:</b> 300x, 310x</color>
        ref over ALS_PARTICIPANT_HANDLER, ALS_DB
            GET Participants - [[https://docs.mojaloop.live/mojaloop-technical-overview/account-lookup-service/als-get-participants.html Get Oracle Routing Config Sequence]]
            |||
        end ref

        '********************* Retrieve Oracle Routing Information - END ************************

        |||

        '********************* Fetch Oracle Routing Information - END ************************

        '********************* Retrieve Switch Routing Information - START ************************

        ALS_PARTICIPANT_HANDLER <-> ALS_DB: Get Switch Routing Config\n<color #FF0000><b>Error code:</b> 300x, 310x</color>
        ref over ALS_PARTICIPANT_HANDLER, ALS_DB
            |||
            GET Participants - [[https://docs.mojaloop.live/mojaloop-technical-overview/account-lookup-service/als-get-participants.html Get Switch Routing Config Sequence]]
            |||
        end ref

        '********************* Retrieve Switch Routing Information - END ************************
        |||

        '********************* Validate Participant - START ************************
        group Validate Participant
            loop for Participant in ParticipantLis

                ALS_PARTICIPANT_HANDLER -> ALS_PARTICIPANT_HANDLER: Validate that Participant == FSPIOP-Source\n<color #FF0000><b>Error code:</b> 3100</color>
                ALS_PARTICIPANT_HANDLER -> ALS_PARTICIPANT_HANDLER: Validate all {TYPES} are the same\n<color #FF0000><b>Error code:</b> 3100</color>

            end loop

            ALS_PARTICIPANT_HANDLER -> ALS_CENTRALSERVICE_PARTICIPANT_DAO: Request participant information for {TYPE}\n<color #FF0000><b>Error code:</b> 200x</color>
            activate ALS_CENTRALSERVICE_PARTICIPANT_DAO

            ALS_CENTRALSERVICE_PARTICIPANT_DAO -> CENTRALSERVICE_API: GET - /participants/{PARTICIPANT.fspId}\n<color #388724><b>Response code:</b> 200</color> \n<color #FF0000><b>Error code:</b> 200x, 310x, 320x</color>
            activate CENTRALSERVICE_API
            CENTRALSERVICE_API --> ALS_CENTRALSERVICE_PARTICIPANT_DAO: Return participant information
            deactivate CENTRALSERVICE_API

            ALS_CENTRALSERVICE_PARTICIPANT_DAO --> ALS_PARTICIPANT_HANDLER: Return participant information

            deactivate ALS_CENTRALSERVICE_PARTICIPANT_DAO

            ALS_PARTICIPANT_HANDLER -> ALS_PARTICIPANT_HANDLER: Validate participant\n<color #FF0000><b>Error code:</b> 320x</color>
        end group
        '********************* Validate Participant - END ************************

        alt {CURRENCY} not Provided OR no matching currency found in list of Endpoints

            '********************* Create Participant Information - START ************************

            ALS_PARTICIPANT_HANDLER -> ALS_PARTICIPANT_ORACLE_DAO: Create participant's FSP details\nPOST - /participants\n<color #FF0000><b>Error code:</b> 200x, 310x, 320x</color>
            activate ALS_PARTICIPANT_ORACLE_DAO
            ALS_PARTICIPANT_ORACLE_DAO -> ORACLE_API: Create participant's FSP details\nPOST - /participants\n<color #388724><b>Response code:</b> 204</color> \n<color #FF0000><b>Error code:</b> 200x, 310x, 320x</color>
            activate ORACLE_API

            ORACLE_API --> ALS_PARTICIPANT_ORACLE_DAO: Return result of Participant Create request
            deactivate ORACLE_API

            ALS_PARTICIPANT_ORACLE_DAO --> ALS_PARTICIPANT_HANDLER: Return result of Participant Create request
            deactivate ALS_PARTICIPANT_ORACLE_DAO

            '********************* Create Participant Information - END ************************

            '********************* Get PayerFSP Participant Information - START ************************

            ALS_PARTICIPANT_HANDLER -> ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO: Retrieve the PayerFSP Participant Callback Endpoint\n<color #FF0000><b>Error code:</b> 200x, 310x, 320x</color>
            activate ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO
            ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO -> CENTRALSERVICE_API: Retrieve the PayerFSP Participant Callback Endpoint\nGET - /participants/{FSPIOP-Source}/endpoints\n<color #388724><b>Response code:</b> 200</color> \n<color #FF0000><b>Error code:</b> 200x, 310x, 320x</color>
            activate CENTRALSERVICE_API
            CENTRALSERVICE_API --> ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO: List of PayerFSP Participant Callback Endpoints
            deactivate CENTRALSERVICE_API
            ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO --> ALS_PARTICIPANT_HANDLER: List of PayerFSP Participant Callback Endpoints
            deactivate ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO

            ALS_PARTICIPANT_HANDLER -> ALS_PARTICIPANT_HANDLER: Match PayerFSP Participant Callback Endpoints for\nFSPIOP_CALLBACK_URL_PARTICIPANT_BATCH_PUT

            '********************* Get PayerFSP Participant Information - END ************************

            ALS_PARTICIPANT_HANDLER --> ALS_API: Return list of Participant information
            ALS_API ->> PAYER_FSP: Callback: PUT - /participants/{requestId}

        else Empty list of End-Points returned or Error occurred

            '********************* Get PayerFSP Participant Information - START ************************

            ALS_PARTICIPANT_HANDLER -> ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO: Retrieve the PayerFSP Participant Callback Endpoint\n<color #FF0000><b>Error code:</b> 200x, 310x, 320x</color>
            activate ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO
            ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO -> CENTRALSERVICE_API: Retrieve the PayerFSP Participant Callback Endpoint\nGET - /participants/{FSPIOP-Source}/endpoints\n<color #388724><b>Response code:</b> 200</color> \n<color #FF0000><b>Error code:</b> 200x, 310x, 320x</color>
            activate CENTRALSERVICE_API
            CENTRALSERVICE_API --> ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO: List of PayerFSP Participant Callback Endpoints
            deactivate CENTRALSERVICE_API
            ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO --> ALS_PARTICIPANT_HANDLER: List of PayerFSP Participant Callback Endpoints
            deactivate ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO

            ALS_PARTICIPANT_HANDLER -> ALS_PARTICIPANT_HANDLER: Match Participant Callback Endpoints for\nFSPIOP_CALLBACK_URL_PARTICIPANT_BATCH_PUT_ERROR

            '********************* Get PayerFSP Participant Information - END ************************

            ALS_PARTICIPANT_HANDLER --> ALS_API: Handle error\n<color #FF0000><b>Error code:</b> 200x, 310x, 320x</color>
            ALS_API ->> PAYER_FSP: Callback: PUT - /participants/{requestId}/error
        end alt
        deactivate ALS_API

        deactivate ALS_PARTICIPANT_HANDLER
    end loop
end
@enduml
