/'*****
 License
 --------------
 Copyright © 2017 Bill & Melinda Gates Foundation
 The Mojaloop files are made available by the Bill & Melinda Gates Foundation under the Apache License, Version 2.0 (the "License") and you may not use these files except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, the Mojaloop files are distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
 Contributors
 --------------
 This is the official list of the Mojaloop project contributors for this file.
 Names of the original copyright holders (individuals or organizations)
 should be listed with a '*' in the first column. People who have
 contributed from an organization can be listed under the organization
 that actually holds the copyright for their contributions (see the
 Gates Foundation organization for an example). Those individuals should have
 their names indented and be marked with a '-'. Email address can be added
 optionally within square brackets <email>.
 * Gates Foundation
 - Name Surname <name.surname@gatesfoundation.com>

 * Rajiv Mothilal <rajiv.mothilal@modusbox.com>
 --------------
 ******'/


@startuml
' declate title
title 7.1.0 Get Party Details

autonumber
' Actor Keys:
' boundary - APIs/Interfaces, etc
' entity - Database Access Objects
' database - Database Persistance Store

' declare actors
actor "Payer FSP" as PAYER_FSP
actor "Payee FSP" as PAYEE_FSP
boundary "Account Lookup Service" as ALS_API
control "ALS Participant Handler" as ALS_PARTICIPANT_HANDLER
entity "ALS CentralService Endpoint DAO" as ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO
entity "ALS CentralService Participant DAO" as ALS_CENTRALSERVICE_PARTICIPANT_DAO
'entity "ALS Participant Oracle DAO" as ALS_PARTICIPANT_ORACLE_DAO
entity "ALS Parties FSP DAO" as ALS_PARTIES_FSP_DAO
database "ALS Database" as ALS_DB
boundary "Oracle Service API" as ORACLE_API
boundary "Central Service API" as CENTRALSERVICE_API

box "Financial Service Provider" #LightGrey
participant PAYER_FSP
end box

box "Account Lookup Service" #LightYellow
participant ALS_API
participant ALS_PARTICIPANT_HANDLER
participant ALS_DB
participant ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO
participant ALS_CENTRALSERVICE_PARTICIPANT_DAO
participant ALS_PARTIES_FSP_DAO
end box

box "Central Services" #LightGreen
participant CENTRALSERVICE_API
end box

box "ALS Oracle Service/Adapter" #LightBlue
participant ORACLE_API
end box

box "Financial Service Provider" #LightGrey
participant PAYEE_FSP
end box

' START OF FLOW

group Get Party Details
    PAYER_FSP --> ALS_API: Request to get parties's FSP details \nGET - /parties/{TYPE}/{ID}?currency={CURRENCY}. \n<color #388724><b>Response code:</b> 202</color> \n<color #FF0000><b>Error code:</b> 200zx, 300x, 310x, 320x</color>
    activate ALS_API
    ALS_API -> ALS_API: Validate request against Mojaloop Interface Specification. \n<color #FF0000><b>Error code:</b> 300x, 310x</color>
    ALS_API -> ALS_PARTICIPANT_HANDLER: Request to get parties's FSP details.
    deactivate ALS_API

    alt oracleEndpoint match found & parties information retrieved
        activate ALS_PARTICIPANT_HANDLER

        '********************* Retrieve Oracle Routing Information - START ************************

        ALS_PARTICIPANT_HANDLER <-> ALS_DB: Get Oracle Routing Config. \n<color #FF0000><b>Error code:</b> 200x, 310x, 320x</color>
        ref over ALS_PARTICIPANT_HANDLER
            GET Participants - <b>Get Oracle Routing Config Sequence</b>
        end ref

        '********************* Retrieve Oracle Routing Information - END ************************
        |||
        '********************* Retrieve Switch Routing Information - START ************************

        ALS_PARTICIPANT_HANDLER <-> ALS_DB: Get Switch Routing Config. \n<color #FF0000><b>Error code:</b> 200x, 310x, 320x</color>
        ref over ALS_PARTICIPANT_HANDLER
            GET Participants - <b>Get Switch Routing Config Sequence</b>
        end ref


        '********************* Retrieve Switch Routing Information - END ************************
        |||
        '********************* Validate Participant - START ************************

        group Validate FSPIOP-Source Participant
            ALS_PARTICIPANT_HANDLER -> ALS_CENTRALSERVICE_PARTICIPANT_DAO: Request FSPIOP-Source participant information. \n<color #FF0000><b>Error code:</b> 200x</color>
            activate ALS_CENTRALSERVICE_PARTICIPANT_DAO

            ALS_CENTRALSERVICE_PARTICIPANT_DAO -> CENTRALSERVICE_API: GET - /participants/{FSPIOP-Source}. \n<color #FF0000><b>Error code:</b> 200x, 310x, 320x</color>
            activate CENTRALSERVICE_API
            CENTRALSERVICE_API -> ALS_CENTRALSERVICE_PARTICIPANT_DAO: Return FSPIOP-Source participant information
            deactivate CENTRALSERVICE_API

            ALS_CENTRALSERVICE_PARTICIPANT_DAO -> ALS_PARTICIPANT_HANDLER: Return FSPIOP-Source participant information

            deactivate ALS_CENTRALSERVICE_PARTICIPANT_DAO

            ALS_PARTICIPANT_HANDLER -> ALS_PARTICIPANT_HANDLER: Validate FSPIOP-Source participant. \n<color #FF0000><b>Error code:</b> 320x</color>
        end group

        '********************* Validate Participant - END ************************
        |||

        '********************* Request Oracle Participant Information - START ************************

        ALS_PARTICIPANT_HANDLER <-> ORACLE_API: Get Participant Information for PayeeFSP.  \n<color #FF0000><b>Error code:</b> 200x, 310x, 320x</color>
        ref over ALS_PARTICIPANT_HANDLER
            GET Participants - <b>Request Participant Information from Oracle Sequence</b>
        end ref

        '********************* Request Oracle Participant Information - END ************************
        |||
        '********************* Request Parties Information - START ************************

        ALS_PARTICIPANT_HANDLER -> ALS_PARTIES_FSP_DAO: Request Parties information from FSP.\n<color #FF0000><b>Error code:</b> 200x</color>

        activate ALS_PARTIES_FSP_DAO
        ALS_PARTIES_FSP_DAO --> PAYEE_FSP: Parties Callback to Destination: GET - /parties/{TYPE}/{ID}?currency={CURRENCY}. \n<color #388724><b>Response code:</b> 202</color> \n<color #FF0000><b>Error code:</b> 200x, 310x, 320x</color>
        deactivate ALS_PARTIES_FSP_DAO
        activate PAYEE_FSP

        PAYEE_FSP --> ALS_API: Callback with Participant Information: PUT - /parties/{TYPE}/{ID}?currency={CURRENCY}. \n<color #FF0000><b>Error code:</b> 200x, 300x, 310x, 320x</color>
        deactivate PAYEE_FSP

        activate ALS_API
        ALS_API -> ALS_API: Validate request against Mojaloop Interface Specification. \n<color #FF0000><b>Error code:</b> 300x, 310x</color>
        ALS_API -> ALS_PARTICIPANT_HANDLER: Process Participant Callback Information for PUT
        deactivate ALS_API

        '********************* Request Parties Information - END ************************

        '********************* Get PayerFSP Participant Information - START ************************

        ALS_PARTICIPANT_HANDLER -> ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO: Retrieve the PayerFSP Participant Callback End-point. \n<color #FF0000><b>Error code:</b> 200x</color>
        activate ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO
        ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO -> CENTRALSERVICE_API: Retrieve the PayerFSP Participant Callback End-point - GET /participants/{FSPIOP-Source}/endpoints. \n<color #FF0000><b>Error code:</b> 200x, 310x, 320x</color>
        activate CENTRALSERVICE_API
        CENTRALSERVICE_API -> ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO: List of PayerFSP Participant Callback End-points
        deactivate CENTRALSERVICE_API
        ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO -> ALS_PARTICIPANT_HANDLER: List of PayerFSP Participant Callback End-points
        deactivate ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO

        ALS_PARTICIPANT_HANDLER -> ALS_PARTICIPANT_HANDLER: Match PayerFSP Participant Callback End-points for `FSPIOP_CALLBACK_URL_PARTIES_PUT`

        '********************* Get PayerFSP Participant Information - END ************************

        ALS_PARTICIPANT_HANDLER -> ALS_API: Send Participant Information to PayerFSP.
        activate ALS_API
        ALS_API --> PAYER_FSP: Callback with Parties Information: PUT - /parties/{TYPE}/{ID}?currency={CURRENCY}
        deactivate ALS_API

    else Empty list of End-Points returned for either (PayeeFSP or Oracle) config information or Error occurred for PayerFSP

        '********************* Get PayerFSP Participant Information - START ************************

        ALS_PARTICIPANT_HANDLER -> ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO: Retrieve the PayerFSP Participant Callback End-point. \n<color #FF0000><b>Error code:</b> 200x, 310x, 320x</color>
        activate ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO
        ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO -> CENTRALSERVICE_API: Retrieve the PayerFSP Participant Callback End-point - GET /participants/{FSPIOP-Source}/endpoints. \n<color #388724><b>Response code:</b> 200</color> \n<color #FF0000><b>Error code:</b> 200x, 310x, 320x</color>
        activate CENTRALSERVICE_API
        CENTRALSERVICE_API -> ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO: List of PayerFSP Participant Callback End-points
        deactivate CENTRALSERVICE_API
        ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO -> ALS_PARTICIPANT_HANDLER: List of PayerFSP Participant Callback End-points
        deactivate ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO

        ALS_PARTICIPANT_HANDLER -> ALS_PARTICIPANT_HANDLER: Match PayerFSP Participant Callback End-points for `FSPIOP_CALLBACK_URL_PARTIES_PUT_ERROR`

        '********************* Get PayerFSP Participant Information - END ************************

        ALS_PARTICIPANT_HANDLER -> ALS_API: Return \n<color #FF0000><b>Error code:</b> 200x, 310x, 320x</color>
        activate ALS_API
        ALS_API --> PAYER_FSP: Callback: PUT - /participants/{TYPE}/{ID}/error
        deactivate ALS_API
    else Empty list of End-Points returned for PayerFSP config information or Error occurred for PayeeFSP

        '********************* Get PayeeFSP Participant Information - START ************************

        ALS_PARTICIPANT_HANDLER -> ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO: Retrieve the PayeeFSP Participant Callback End-point. \n<color #FF0000><b>Error code:</b> 200x, 310x, 320x</color>
        activate ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO
        ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO -> CENTRALSERVICE_API: Retrieve the PayeeFSP Participant Callback End-point - GET /participants/{FSPIOP-Source}/endpoints. \n<color #388724><b>Response code:</b> 200</color> \n<color #FF0000><b>Error code:</b> 200x, 310x, 320x</color>
        activate CENTRALSERVICE_API
        CENTRALSERVICE_API -> ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO: List of PayeeFSP Participant Callback End-points
        deactivate CENTRALSERVICE_API
        ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO -> ALS_PARTICIPANT_HANDLER: List of PayeeFSP Participant Callback End-points
        deactivate ALS_CENTRALSERVICE_ENDPOINT_CONFIG_DAO

        ALS_PARTICIPANT_HANDLER -> ALS_PARTICIPANT_HANDLER: Match PayeeFSP Participant Callback End-points for `FSPIOP_CALLBACK_URL_PARTIES_PUT_ERROR`

        '********************* Get PayerFSP Participant Information - END ************************

        ALS_PARTICIPANT_HANDLER -> ALS_API: Return \n<color #FF0000><b>Error code:</b> 200x, 310x, 320x</color>
        activate ALS_API
        ALS_API --> PAYEE_FSP: Callback: PUT - /participants/{TYPE}/{ID}/error
        deactivate ALS_API
    else Empty list of switchEndpoint results returned
        ALS_PARTICIPANT_HANDLER -> ALS_PARTICIPANT_HANDLER: Handle error\n<color #FF0000><b>Error code:</b> 200x</color>
        hnote right ALS_PARTICIPANT_HANDLER #red
            Error Handling Framework
        end note
    end alt

    deactivate ALS_PARTICIPANT_HANDLER
end
@enduml
