/'*****
 License
 --------------
 Copyright © 2017 Bill & Melinda Gates Foundation
 The Mojaloop files are made available by the Bill & Melinda Gates Foundation under the Apache License, Version 2.0 (the "License") and you may not use these files except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, the Mojaloop files are distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
 Contributors
 --------------
 This is the official list of the Mojaloop project contributors for this file.
 Names of the original copyright holders (individuals or organizations)
 should be listed with a '*' in the first column. People who have
 contributed from an organization can be listed under the organization
 that actually holds the copyright for their contributions (see the
 Gates Foundation organization for an example). Those individuals should have
 their names indented and be marked with a '-'. Email address can be added
 optionally within square brackets <email>.
 * Gates Foundation
 - Name Surname <name.surname@gatesfoundation.com>

 * Rajiv Mothilal <rajiv.mothilal@modusbox.com>
 --------------
 ******'/


@startuml
' declate title
title 7.2.0 Get Parties Details

autonumber
' Actor Keys:
' boundary - APIs/Interfaces, etc
' entity - Database Access Objects
' database - Database Persistance Store

' declare actors
actor "Payer FSP" as PAYER_FSP
boundary "Account Lookup Service" as ALS
control "Parties Handler" as PARTIES_HANDLER
entity "Account Lookup Service API" as ALS
entity "Participant DAO" as PARTICIPANT_DAO
database "Central Ledger Database" as DB
entity "Pathfinder Service" as PATHFINDER_SERVICE
actor "GSMA Pathfinder" as PATHFINDER
actor "Payee FSP" as PAYEE_FSP

box "Account Lookup Service" #LightYellow
participant ALS
participant PARTIES_HANDLER
participant PARTICIPANT_DAO
participant DB
end box

box "Pathfinder Library" #LightBlue
participant PATHFINDER_SERVICE
end box

participant PATHFINDER
participant PAYEE_FSP

' start flow

activate PAYER_FSP
group Get Party's Details
    PAYER_FSP -> ALS: Request to get party's details \nGET - /parties/{Type}/{ID}
    activate ALS
    ALS -> PARTIES_HANDLER: Get Party by ID and Type \n(PartiesByTypeAndID)
    activate PARTIES_HANDLER
    PARTIES_HANDLER ->PARTIES_HANDLER: Validate MSISDN
    PARTIES_HANDLER ->PARTICIPANT_DAO: Fetch Source Party's details \n(handleMSISDNPartyRequest)\n<color #FF0000><b>Error code:</b> 3200</color>
    activate PARTICIPANT_DAO
    PARTICIPANT_DAO -> DB: Fetch Source Party Error Endpoint \n(getParticipantEndpointByName)
    activate DB
    hnote over DB #lightyellow
        participantEndpoint
    end note
    DB --> PARTICIPANT_DAO: Return Party Error Endpoint
    deactivate DB
    PARTICIPANT_DAO --> PARTIES_HANDLER: Return Party Error Endpoint
    deactivate PARTICIPANT_DAO
    PARTIES_HANDLER -> PATHFINDER_SERVICE: Query Party ID
    activate PATHFINDER_SERVICE
    PATHFINDER_SERVICE -> PATHFINDER: Query Party
    activate PATHFINDER
    PATHFINDER -> PATHFINDER_SERVICE: Return Mobile Country Code \nand Network Code
    deactivate PATHFINDER
    PATHFINDER_SERVICE -> PARTIES_HANDLER: Return MCC & MNC
    deactivate PATHFINDER_SERVICE
    PARTIES_HANDLER ->PARTICIPANT_DAO: Fetch Participant Name\n<color #FF0000><b>Error code:</b> 3200</color>
    activate PARTICIPANT_DAO
    PARTICIPANT_DAO -> DB: Fetch Participant Name \n(getParticipantNameFromMccMnc)
    activate DB
    hnote over DB #lightyellow
        participantMno
    end note
    DB --> PARTICIPANT_DAO: Return Participant Name
    deactivate DB
    PARTICIPANT_DAO --> PARTIES_HANDLER: Return Participant Name
    deactivate PARTICIPANT_DAO
    PARTIES_HANDLER ->PARTICIPANT_DAO: Fetch Target Participant's details \n(handleMSISDNPartyRequest)\n<color #FF0000><b>Error code:</b> 3200</color>
    activate PARTICIPANT_DAO
    PARTICIPANT_DAO -> DB: Fetch Target Participant Endpoint \n(getParticipantEndpointByName)
    activate DB
    hnote over DB #lightyellow
        participantEndpoint
    end note
    DB --> PARTICIPANT_DAO: Return Target Participant Endpoint
    deactivate DB
    PARTICIPANT_DAO --> PARTIES_HANDLER: Return Target Participant Endpoint
    deactivate PARTICIPANT_DAO
    PARTIES_HANDLER -> ALS: Return Success
    PARTIES_HANDLER -> PAYEE_FSP: Forward Request to Target Participant with Updated Headers
    deactivate PARTIES_HANDLER
    ALS -->PAYER_FSP: Return Success 202
    deactivate ALS
    deactivate PAYER_FSP
end
@enduml
