/'*****
 License
 --------------
 Copyright © 2017 Bill & Melinda Gates Foundation
 The Mojaloop files are made available by the Bill & Melinda Gates Foundation under the Apache License, Version 2.0 (the "License") and you may not use these files except in compliance with the License. You may obtain a copy of the License at
 http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, the Mojaloop files are distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
 Contributors
 --------------
 This is the official list of the Mojaloop project contributors for this file.
 Names of the original copyright holders (individuals or organizations)
 should be listed with a '*' in the first column. People who have
 contributed from an organization can be listed under the organization
 that actually holds the copyright for their contributions (see the
 Gates Foundation organization for an example). Those individuals should have
 their names indented and be marked with a '-'. Email address can be added
 optionally within square brackets <email>.
 * Gates Foundation
 - Name Surname <name.surname@gatesfoundation.com>

 * Rajiv Mothilal <rajiv.mothilal@modusbox.com>
 --------------
 ******'/


@startuml
' declate title
title 7.2.1 Post Participants Details

autonumber
' Actor Keys:
' boundary - APIs/Interfaces, etc
' entity - Database Access Objects
' database - Database Persistance Store

' declare actors
actor "PAYER_FSP" as PAYER_FSP
boundary "Account Lookup Service" as ALS
control "Parties Handler" as PARTIES_HANDLER
entity "Account Lookup Service API" as ALS
entity "Participant DAO" as PARTICIPANT_DAO
database "Central Ledger Database" as DB
actor "Payee_FSP" as PAYEE_FSP

box "Account Lookup Service" #LightYellow
participant ALS
participant PARTIES_HANDLER
participant PARTICIPANT_DAO
participant DB
end box

participant PAYEE_FSP

' start flow

activate PAYER_FSP
group Put Party's Details
    PAYER_FSP -> ALS: Callback for the Get Party's request   \nPUT - /parties/{Type}/{ID}
    note right of PAYER_FSP #yellow
        Message:
        party: {
            partyIdInfo: {
                “partyIdType”: “PERSONAL_ID”,
                “partyIdentifier”: “1551212”,
                “partySubIdOrType”: “License”,
                “fspId”: “1234”
            },
            merchantClassificationCode: 4321,
            “name”: “Justin Trudeau”,
            “personalInfo”: {
                “complexName”: {
                    “firstName”: “Justin”,
                    “middleName”: “Pierre”,
                    “lastName”: “Trudeau”
                },
                “dateOfBirth”: “1971-12-25”
            }
        }
    end note
    activate ALS
    ALS -> PARTIES_HANDLER: Put Party by ID and Type \n(PartiesByTypeAndID2)
    activate PARTIES_HANDLER
    PARTIES_HANDLER ->PARTIES_HANDLER: Validate MSISDN
    PARTIES_HANDLER ->PARTICIPANT_DAO: Fetch Target Participant's details \n(handleMSISDNPartyRequest)\n<color #FF0000><b>Error code:</b> 3200</color>
    activate PARTICIPANT_DAO
    PARTICIPANT_DAO -> DB: Fetch Target Participant Endpoint \n(getParticipantEndpointByName)
    activate DB
    hnote over DB #lightyellow
        participantEndpoint
    end note
    DB --> PARTICIPANT_DAO: Return Target Participant Endpoint
    deactivate DB
    PARTICIPANT_DAO --> PARTIES_HANDLER: Return Target Participant Endpoint
    deactivate PARTICIPANT_DAO
    PARTIES_HANDLER -> ALS: Return Success
    PARTIES_HANDLER -> PAYEE_FSP: Forward Request to Target Participant
    deactivate PARTIES_HANDLER
    ALS -->PAYER_FSP: Return Success 200
    deactivate ALS
    deactivate PAYER_FSP
end
@enduml
